# Diarización por lote, limpieza y anchors de alta confianza

Notebook para:

- procesar todos los `.wav` de una carpeta
- diarizar con **2 hablantes**
- usar **exclusive speaker diarization** si está disponible
- detectar **zonas solapadas** a partir de la diarización regular
- escoger **anchors** por hablante para la siguiente fase de identificación agente/cliente

In [1]:
%pip install -q -r ~/TFM_ProcesadoDeAudios/requirements.txt

print("Requisitos instalados correctamente.")

Note: you may need to restart the kernel to use updated packages.
Requisitos instalados correctamente.

In [2]:
# Preparación mínima del entorno para el notebook

import os
from pathlib import Path

print("Notebook listo para importar librerías")

Notebook listo para importar librerías

In [3]:
import random
import numpy as np
import pandas as pd
import soundfile as sf
import torch
import openpyxl
from google.cloud import storage
from pyannote.audio import Pipeline
from IPython.display import clear_output

print("Imports de librerias cargados correctamente.")

Imports de librerias cargados correctamente.

In [4]:
# =========================
# CONFIGURACIÓN GENERAL
# =========================

HF_TOKEN = "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"

PROJECT_DIR = Path("/home/jupyter/TFM_ProcesadoDeAudios")

# Fuente en GCS: audios limpios generados en el notebook de EDA/limpieza
GCS_CLEAN_AUDIO_PREFIX = "gs://catedras_audio_detection/pipelineA/procesados_UNAV/clean_audios/"

# Carpeta local temporal para ejecutar diarización
INPUT_DIR = PROJECT_DIR / "data" / "diarization_input_clean_audios"

# Salidas locales de diarización
OUTPUT_DIR = PROJECT_DIR / "data" / "diarization_outputs"

# Salidas persistentes en GCS para checkpoints y reanudación
GCS_DIARIZATION_OUTPUT_PREFIX = "gs://catedras_audio_detection/pipelineA/procesados_UNAV/diarization_outputs/"

# Control de ejecución robusta
RE_DIARIZAR = False                  # False = reanuda/salta audios ya procesados
BATCH_SAVE_EVERY = 25               # guarda consolidado y sube checkpoint cada 25 audios
RESUME_FROM_GCS = True               # intenta recuperar outputs ya subidos a GCS
UPLOAD_EACH_AUDIO_TO_GCS = True      # sube outputs por audio apenas termina cada audio

SEGMENTS_DIR = OUTPUT_DIR / "segments"
ANCHOR_SEGMENTS_DIR = OUTPUT_DIR / "anchor_segments"

INPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
SEGMENTS_DIR.mkdir(parents=True, exist_ok=True)
ANCHOR_SEGMENTS_DIR.mkdir(parents=True, exist_ok=True)

# Parámetros del pipeline
NUM_SPEAKERS = 2
USE_EXCLUSIVE_DIARIZATION = True

# Limpieza para exportar segmentos "útiles"
MIN_SEGMENT_DURATION_SEC = 0.70
MIN_RMS_DBFS = -40.0
MAX_GAP_MERGE_SEC = 0.50

# Reglas más estrictas para elegir anchors de identidad
MIN_ANCHOR_DURATION_SEC = 1.20
MAX_OVERLAP_RATIO_FOR_ANCHOR = 0.00
INITIAL_EXCLUDE_SEC_FOR_ANCHORS = 1.50
ANCHORS_PER_SPEAKER = 3

# Auditoría
N_AUDIT = 5
RANDOM_SEED = 42
EXPORT_ANCHORS_FOR_AUDIT = True

print("GCS_CLEAN_AUDIO_PREFIX:", GCS_CLEAN_AUDIO_PREFIX)
print("INPUT_DIR:", INPUT_DIR)
print("OUTPUT_DIR:", OUTPUT_DIR)
print("GCS_DIARIZATION_OUTPUT_PREFIX:", GCS_DIARIZATION_OUTPUT_PREFIX)
print("RE_DIARIZAR:", RE_DIARIZAR)
print("BATCH_SAVE_EVERY:", BATCH_SAVE_EVERY)
print("SEGMENTS_DIR:", SEGMENTS_DIR)
print("ANCHOR_SEGMENTS_DIR:", ANCHOR_SEGMENTS_DIR)

GCS_CLEAN_AUDIO_PREFIX: gs://catedras_audio_detection/pipelineA/procesados_UNAV/clean_audios/
INPUT_DIR: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_input_clean_audios
OUTPUT_DIR: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs
GCS_DIARIZATION_OUTPUT_PREFIX: gs://catedras_audio_detection/pipelineA/procesados_UNAV/diarization_outputs/
RE_DIARIZAR: False
BATCH_SAVE_EVERY: 25
SEGMENTS_DIR: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/segments
ANCHOR_SEGMENTS_DIR: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/anchor_segments

In [5]:
# Cargar pipeline una sola vez

pipeline = Pipeline.from_pretrained(
    "pyannote/speaker-diarization-community-1",
    token=HF_TOKEN
)

print("pipeline cargada")

pipeline cargada

In [6]:
# Funciones auxiliares

def load_audio_as_mono(audio_path: Path):
    audio, sr = sf.read(audio_path, always_2d=True)
    waveform = torch.from_numpy(audio.T).float()
    waveform_mono = waveform.mean(dim=0, keepdim=True)
    audio_mono = waveform_mono.squeeze(0).numpy()
    duration_sec = len(audio_mono) / sr
    return waveform_mono, audio_mono, sr, duration_sec


DIARIZATION_SEGMENT_COLUMNS = [
    "audio_file",
    "audio_stem",
    "start",
    "end",
    "duration",
    "speaker",
]

SCORED_SEGMENT_COLUMNS = [
    "segment_id_raw",
    "audio_file",
    "audio_stem",
    "start",
    "end",
    "duration",
    "speaker",
    "rms_dbfs",
    "overlap_duration_sec",
    "overlap_ratio",
    "valid_export",
    "valid_anchor",
    "drop_reasons",
    "anchor_reasons",
]

ANCHOR_SEGMENT_COLUMNS = SCORED_SEGMENT_COLUMNS + ["anchor_rank"]


def annotation_to_df(annotation, audio_path: Path):
    rows = []

    # Cada fila = un segmento de diarización
    for turn, _, speaker in annotation.itertracks(yield_label=True):
        rows.append({
            "audio_file": audio_path.name,
            "audio_stem": audio_path.stem,
            "start": float(turn.start),
            "end": float(turn.end),
            "duration": float(turn.end - turn.start),
            "speaker": speaker
        })

    # IMPORTANTE:
    # Aunque no haya segmentos, devolvemos columnas.
    # Si no, pandas escribe un CSV completamente vacío y luego read_csv revienta con EmptyDataError.
    df = pd.DataFrame(rows, columns=DIARIZATION_SEGMENT_COLUMNS)

    # Ordenar siempre por tiempo
    if not df.empty:
        df = df.sort_values(["start", "end"]).reset_index(drop=True)

    return df


def merge_adjacent_same_speaker(df_segments: pd.DataFrame, max_gap_sec: float):
    if df_segments.empty:
        return df_segments.copy()

    df = df_segments.sort_values(["start", "end"]).reset_index(drop=True)
    merged_rows = []
    current = df.iloc[0].to_dict()

    for _, row in df.iloc[1:].iterrows():
        gap = float(row["start"]) - float(current["end"])
        same_speaker = row["speaker"] == current["speaker"]

        # Si es el mismo speaker y la pausa es corta, unir
        if same_speaker and gap <= max_gap_sec:
            current["end"] = max(float(current["end"]), float(row["end"]))
            current["duration"] = float(current["end"] - current["start"])
        else:
            merged_rows.append(current.copy())
            current = row.to_dict()

    merged_rows.append(current.copy())
    merged_df = pd.DataFrame(merged_rows)

    if not merged_df.empty:
        merged_df = merged_df.sort_values(["start", "end"]).reset_index(drop=True)

    return merged_df


def compute_overlap_intervals(df_regular: pd.DataFrame):
    if df_regular.empty:
        return []

    events = []

    # Abrir + cerrar cada segmento regular
    for _, row in df_regular.iterrows():
        start = float(row["start"])
        end = float(row["end"])

        if end <= start:
            continue

        events.append((start, 1))
        events.append((end, -1))

    # Si uno termina justo cuando otro empieza,
    # eso NO cuenta como overlap
    events.sort(key=lambda x: (x[0], x[1]))

    overlap_intervals = []
    active = 0
    prev_t = None

    for t, delta in events:
        if prev_t is not None and t > prev_t and active > 1:
            overlap_intervals.append((prev_t, t))

        active += delta
        prev_t = t

    # Unir intervalos contiguos por seguridad
    merged = []

    for start, end in overlap_intervals:
        if not merged:
            merged.append([start, end])
        elif start <= merged[-1][1]:
            merged[-1][1] = max(merged[-1][1], end)
        else:
            merged.append([start, end])

    return [(float(s), float(e)) for s, e in merged]


def interval_overlap_duration(start: float, end: float, intervals):
    total = 0.0

    for ov_start, ov_end in intervals:
        inter_start = max(start, ov_start)
        inter_end = min(end, ov_end)

        if inter_end > inter_start:
            total += inter_end - inter_start

    return total


def rms_dbfs(x):
    x = np.asarray(x, dtype=np.float32)

    if x.size == 0:
        return -120.0

    rms = np.sqrt(np.mean(np.square(x)))

    if rms <= 1e-10:
        return -120.0

    return float(20.0 * np.log10(rms))


def build_scored_segments(df_segments: pd.DataFrame, audio_mono, sr: int, overlap_intervals):
    if df_segments.empty:
        return pd.DataFrame(columns=SCORED_SEGMENT_COLUMNS)

    rows = []

    # Enumerar aquí garantiza que raw, valid y anchors hereden el mismo id
    for seg_idx, (_, row) in enumerate(df_segments.iterrows(), start=1):
        start = float(row["start"])
        end = float(row["end"])
        duration = float(row["duration"])

        start_sample = max(0, int(round(start * sr)))
        end_sample = min(len(audio_mono), int(round(end * sr)))

        if end_sample <= start_sample:
            segment_audio = np.array([], dtype=np.float32)
        else:
            segment_audio = audio_mono[start_sample:end_sample]

        seg_rms_dbfs = rms_dbfs(segment_audio)
        overlap_duration_sec = interval_overlap_duration(start, end, overlap_intervals)
        overlap_ratio = overlap_duration_sec / duration if duration > 0 else 0.0

        export_reasons = []

        # Filtros para quedarse en valid
        if duration < MIN_SEGMENT_DURATION_SEC:
            export_reasons.append("short")

        if seg_rms_dbfs < MIN_RMS_DBFS:
            export_reasons.append("low_energy")

        valid_export = len(export_reasons) == 0

        anchor_reasons = list(export_reasons)

        # Filtros extra para anchors
        if duration < MIN_ANCHOR_DURATION_SEC:
            anchor_reasons.append("short_anchor")

        if overlap_ratio > MAX_OVERLAP_RATIO_FOR_ANCHOR:
            anchor_reasons.append("overlap")

        if start < INITIAL_EXCLUDE_SEC_FOR_ANCHORS:
            anchor_reasons.append("initial_window")

        anchor_reasons = sorted(set(anchor_reasons))
        valid_anchor = len(anchor_reasons) == 0

        out = row.to_dict()
        out["segment_id_raw"] = int(seg_idx)
        out["rms_dbfs"] = float(seg_rms_dbfs)
        out["overlap_duration_sec"] = float(overlap_duration_sec)
        out["overlap_ratio"] = float(overlap_ratio)
        out["valid_export"] = bool(valid_export)
        out["valid_anchor"] = bool(valid_anchor)
        out["drop_reasons"] = ";".join(export_reasons)
        out["anchor_reasons"] = ";".join(anchor_reasons)
        rows.append(out)

    df_scored = pd.DataFrame(rows)

    # Orden final por tiempo por si acaso
    df_scored = df_scored.sort_values(["segment_id_raw"]).reset_index(drop=True)

    return df_scored


def select_anchor_segments(df_scored: pd.DataFrame, anchors_per_speaker: int):
    if df_scored.empty:
        return pd.DataFrame(columns=ANCHOR_SEGMENT_COLUMNS)

    # Solo pasan los que cumplen filtros de anchor
    anchors = df_scored[df_scored["valid_anchor"]].copy()

    if anchors.empty:
        return pd.DataFrame(columns=ANCHOR_SEGMENT_COLUMNS)

    # Priorizamos:
    # 1) más largos
    # 2) más energía
    # 3) menos overlap
    # 4) antes en el tiempo si empatan
    anchors = anchors.sort_values(
        by=["speaker", "duration", "rms_dbfs", "overlap_ratio", "start"],
        ascending=[True, False, False, True, True]
    ).copy()

    anchors["anchor_rank"] = anchors.groupby("speaker").cumcount() + 1
    anchors = anchors[anchors["anchor_rank"] <= anchors_per_speaker].reset_index(drop=True)

    return anchors.reindex(columns=ANCHOR_SEGMENT_COLUMNS)


def diarize_audio(audio_path: Path, pipeline):
    waveform_mono, audio_mono, sr, duration_sec = load_audio_as_mono(audio_path)

    output = pipeline(
        {
            "waveform": waveform_mono,
            "sample_rate": sr
        },
        num_speakers=NUM_SPEAKERS
    )

    diarization_regular = output.speaker_diarization
    diarization_exclusive = getattr(output, "exclusive_speaker_diarization", None)

    # Esta se usa solo para medir overlap
    df_regular = annotation_to_df(diarization_regular, audio_path)

    # Esta es la que usamos como salida principal
    if USE_EXCLUSIVE_DIARIZATION and diarization_exclusive is not None:
        diarization_used = diarization_exclusive
        diarization_mode = "exclusive"
    else:
        diarization_used = diarization_regular
        diarization_mode = "regular"

    df_used = annotation_to_df(diarization_used, audio_path)

    # Merge temprano para reducir microfragmentación
    df_used_merged = merge_adjacent_same_speaker(df_used, MAX_GAP_MERGE_SEC)

    # El overlap se estima con la diarización regular
    overlap_intervals = compute_overlap_intervals(df_regular)

    # Aquí ya nace segment_id_raw
    df_scored = build_scored_segments(df_used_merged, audio_mono, sr, overlap_intervals)

    # valid y anchors heredan el mismo segment_id_raw
    df_valid = df_scored[df_scored["valid_export"]].copy().reset_index(drop=True)
    df_anchors = select_anchor_segments(df_scored, ANCHORS_PER_SPEAKER)

    return {
        "diarization_regular": diarization_regular,
        "diarization_used": diarization_used,
        "diarization_mode": diarization_mode,
        "df_regular": df_regular,
        "df_used": df_used,
        "df_used_merged": df_used_merged,
        "df_scored": df_scored,
        "df_valid": df_valid,
        "df_anchors": df_anchors,
        "overlap_intervals": overlap_intervals,
        "sr": sr,
        "duration_sec": duration_sec,
        "audio_mono": audio_mono
    }


def write_csv_atomic(df: pd.DataFrame, path: Path, columns=None):
    """
    Escribe CSV de forma segura:
    - siempre deja header aunque no haya filas
    - escribe primero a .tmp y luego reemplaza
    - evita archivos de 0 bytes si el kernel muere a mitad de escritura
    """
    path.parent.mkdir(parents=True, exist_ok=True)

    df_to_write = df.copy() if df is not None else pd.DataFrame()

    if columns is not None:
        # Si faltan columnas, las crea vacías; si sobran, las conserva al final.
        for col in columns:
            if col not in df_to_write.columns:
                df_to_write[col] = pd.Series(dtype="object")
        extra_cols = [c for c in df_to_write.columns if c not in columns]
        df_to_write = df_to_write[columns + extra_cols]

    tmp_path = path.with_suffix(path.suffix + ".tmp")
    df_to_write.to_csv(tmp_path, index=False)
    tmp_path.replace(path)

    return path


def save_diarization_outputs(audio_path: Path, result: dict, output_dir: Path):
    raw_csv_path = output_dir / f"{audio_path.stem}_raw.csv"
    clean_csv_path = output_dir / f"{audio_path.stem}.csv"
    anchors_csv_path = output_dir / f"{audio_path.stem}_anchors.csv"
    rttm_path = output_dir / f"{audio_path.stem}.rttm"

    # Estos tres CSVs pueden legítimamente tener 0 filas, pero NUNCA deben quedar con 0 bytes.
    write_csv_atomic(result["df_scored"], raw_csv_path, columns=SCORED_SEGMENT_COLUMNS)
    write_csv_atomic(result["df_valid"], clean_csv_path, columns=SCORED_SEGMENT_COLUMNS)
    write_csv_atomic(result["df_anchors"], anchors_csv_path, columns=ANCHOR_SEGMENT_COLUMNS)

    tmp_rttm_path = rttm_path.with_suffix(rttm_path.suffix + ".tmp")
    with open(tmp_rttm_path, "w", encoding="utf-8") as f:
        result["diarization_used"].write_rttm(f)
    tmp_rttm_path.replace(rttm_path)

    return raw_csv_path, clean_csv_path, anchors_csv_path, rttm_path



def export_segments_from_csv(audio_path: Path, csv_path: Path, segments_root: Path):
    df_segments = read_csv_robust(csv_path) if "read_csv_robust" in globals() else pd.read_csv(csv_path)

    out_dir = segments_root / audio_path.stem
    out_dir.mkdir(parents=True, exist_ok=True)

    if df_segments.empty:
        return {
            "audio_file": audio_path.name,
            "segments_folder": str(out_dir),
            "segments_exported": 0
        }

    _, audio_mono, sr, _ = load_audio_as_mono(audio_path)

    exported = 0

    for idx, row in df_segments.iterrows():
        start_sample = max(0, int(round(float(row["start"]) * sr)))
        end_sample = min(len(audio_mono), int(round(float(row["end"]) * sr)))

        if end_sample <= start_sample:
            continue

        segment_audio = audio_mono[start_sample:end_sample]

        # Si existe segment_id_raw, usarlo en el nombre
        if "segment_id_raw" in row.index and pd.notna(row["segment_id_raw"]):
            seg_id = int(row["segment_id_raw"])
        else:
            seg_id = int(idx + 1)

        filename = (
            f"seg_{seg_id:03d}_"
            f"{row['speaker']}_"
            f"{float(row['start']):.2f}s_"
            f"{float(row['end']):.2f}s.wav"
        )

        out_path = out_dir / filename
        sf.write(out_path, segment_audio, sr)
        exported += 1

    return {
        "audio_file": audio_path.name,
        "segments_folder": str(out_dir),
        "segments_exported": exported
    }

In [7]:
# =========================
# CONEXIÓN AUXILIAR A GOOGLE CLOUD STORAGE
# =========================

def split_gcs_uri(gcs_uri: str):
    if not gcs_uri.startswith("gs://"):
        raise ValueError("La ruta debe empezar por 'gs://'")
    
    path = gcs_uri[5:]
    bucket_name, _, prefix = path.partition("/")
    return bucket_name, prefix


gcs_client = storage.Client()

print("Cliente de GCS configurado correctamente.")

Cliente de GCS configurado correctamente.

In [8]:
# =========================
# DESCARGA LOCAL DE AUDIOS LIMPIOS DESDE GCS
# =========================

clean_bucket_name, clean_prefix = split_gcs_uri(GCS_CLEAN_AUDIO_PREFIX)

clean_blobs = [
    blob for blob in gcs_client.list_blobs(clean_bucket_name, prefix=clean_prefix)
    if blob.name.lower().endswith(".wav")
]

print(f"WAVs encontrados en GCS: {len(clean_blobs)}")
print(f"Prefijo revisado: gs://{clean_bucket_name}/{clean_prefix}")

if len(clean_blobs) == 0:
    raise FileNotFoundError(
        f"No se encontraron WAVs en gs://{clean_bucket_name}/{clean_prefix}. "
        "Revisa que el notebook de limpieza haya subido los audios limpios a ese prefijo."
    )

for i, blob in enumerate(clean_blobs, start=1):
    local_path = INPUT_DIR / Path(blob.name).name

    clear_output(wait=True)
    print(f"Descargando audio limpio {i}/{len(clean_blobs)}: {local_path.name}")

    if not local_path.exists():
        blob.download_to_filename(str(local_path))

clear_output(wait=True)
print(f"Descarga completada. Audios limpios disponibles localmente en: {INPUT_DIR}")

Descarga completada. Audios limpios disponibles localmente en: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_input_clean_audios

In [9]:
# Leer automáticamente todos los WAV del folder

wav_files = sorted(INPUT_DIR.glob("*.wav"))

print(f"Se encontraron {len(wav_files)} archivos WAV")

if not wav_files:
    raise FileNotFoundError(f"No se encontraron archivos .wav en: {INPUT_DIR}")

Se encontraron 1200 archivos WAV

In [10]:
# =========================
# DIARIZACIÓN ROBUSTA POR LOTES CON CHECKPOINTS EN GCS
# =========================

# Esta celda está diseñada para ejecuciones largas.
# - Si un audio ya tiene outputs locales o en GCS, se salta cuando RE_DIARIZAR=False.
# - Cada audio procesado se sube a GCS inmediatamente.
# - Cada BATCH_SAVE_EVERY audios se reconstruyen y suben los CSV consolidados.
#
# Corrección importante:
# Los CSVs por audio pueden tener 0 filas, pero NO pueden tener 0 bytes.
# Si encuentra un CSV vacío/corrupto, lo considera inválido y rediariza ese audio.

from pandas.errors import EmptyDataError

summary_csv = OUTPUT_DIR / "diarization_summary.csv"
all_regular_segments_csv = OUTPUT_DIR / "diarization_all_regular_segments.csv"
all_scored_segments_csv = OUTPUT_DIR / "diarization_all_scored_segments.csv"
all_valid_segments_csv = OUTPUT_DIR / "diarization_all_valid_segments.csv"
all_anchor_segments_csv = OUTPUT_DIR / "diarization_all_anchor_segments.csv"

SUMMARY_COLUMNS = [
    "audio_file",
    "audio_stem",
    "sample_rate",
    "duration_sec",
    "diarization_mode",
    "n_regular_segments",
    "n_scored_segments",
    "n_valid_segments",
    "n_anchor_segments",
    "n_speakers",
    "n_overlap_regions",
    "regular_csv_path",
    "raw_csv_path",
    "clean_csv_path",
    "anchors_csv_path",
    "rttm_path",
]

GCS_DIARIZATION_OUTPUT_PREFIX = globals().get(
    "GCS_DIARIZATION_OUTPUT_PREFIX",
    "gs://catedras_audio_detection/pipelineA/procesados_UNAV/diarization_outputs/"
)
RE_DIARIZAR = globals().get("RE_DIARIZAR", False)
BATCH_SAVE_EVERY = globals().get("BATCH_SAVE_EVERY", 100)
RESUME_FROM_GCS = globals().get("RESUME_FROM_GCS", True)
UPLOAD_EACH_AUDIO_TO_GCS = globals().get("UPLOAD_EACH_AUDIO_TO_GCS", True)


def gcs_blob_for_local_path(local_path: Path, gcs_prefix: str):
    bucket_name, prefix = split_gcs_uri(gcs_prefix)
    relative_path = local_path.relative_to(OUTPUT_DIR).as_posix()
    blob_path = f"{prefix}{relative_path}"
    bucket_obj = gcs_client.bucket(bucket_name)
    return bucket_obj.blob(blob_path), bucket_name, blob_path


def upload_file_to_gcs(local_path: Path, gcs_prefix: str):
    if not local_path.exists() or local_path.stat().st_size == 0:
        return False

    blob, _, _ = gcs_blob_for_local_path(local_path, gcs_prefix)
    blob.upload_from_filename(str(local_path))
    return True


def download_file_from_gcs_if_exists(local_path: Path, gcs_prefix: str):
    blob, _, _ = gcs_blob_for_local_path(local_path, gcs_prefix)

    if blob.exists():
        # No descargamos blobs vacíos porque son checkpoints corruptos/incompletos.
        if getattr(blob, "size", None) == 0:
            return False

        local_path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = local_path.with_suffix(local_path.suffix + ".download")
        blob.download_to_filename(str(tmp_path))

        if tmp_path.exists() and tmp_path.stat().st_size > 0:
            tmp_path.replace(local_path)
            return True

        if tmp_path.exists():
            tmp_path.unlink()

    return False


def get_audio_output_paths(audio_path: Path):
    """
    Rutas por audio. Se preservan los nombres históricos:
    - *_raw.csv contiene segmentos puntuados/scored.
    - .csv contiene segmentos válidos.
    - *_anchors.csv contiene anchors.
    - *_regular.csv contiene la diarización regular usada para overlap.
    """
    stem = audio_path.stem
    return {
        "regular": OUTPUT_DIR / f"{stem}_regular.csv",
        "scored": OUTPUT_DIR / f"{stem}_raw.csv",
        "valid": OUTPUT_DIR / f"{stem}.csv",
        "anchors": OUTPUT_DIR / f"{stem}_anchors.csv",
        "rttm": OUTPUT_DIR / f"{stem}.rttm",
    }


def read_csv_robust(path: Path, columns=None):
    """
    Lee un CSV de forma tolerante.
    - Si no existe, devuelve DataFrame vacío con columnas esperadas.
    - Si existe pero tiene 0 bytes o está corrupto, devuelve DataFrame vacío.
    """
    if columns is None:
        columns = []

    if not path.exists() or path.stat().st_size == 0:
        return pd.DataFrame(columns=columns)

    try:
        return pd.read_csv(path)
    except EmptyDataError:
        return pd.DataFrame(columns=columns)
    except Exception as e:
        print(f"Advertencia: no se pudo leer {path.name}: {e}")
        return pd.DataFrame(columns=columns)


def csv_is_usable(path: Path, required_columns=None):
    """
    Un CSV con 0 filas es válido si tiene header.
    Un CSV de 0 bytes NO es válido.
    """
    if required_columns is None:
        required_columns = []

    if not path.exists() or path.stat().st_size == 0:
        return False

    try:
        df_head = pd.read_csv(path, nrows=0)
    except Exception:
        return False

    return all(col in df_head.columns for col in required_columns)


def required_outputs_exist(paths: dict):
    """
    Para saltar un audio, exigimos outputs legibles.
    Los CSVs pueden estar vacíos de filas, pero deben tener columnas.
    """
    csv_checks = {
        "scored": SCORED_SEGMENT_COLUMNS,
        "valid": SCORED_SEGMENT_COLUMNS,
        "anchors": ANCHOR_SEGMENT_COLUMNS,
        "regular": DIARIZATION_SEGMENT_COLUMNS,
    }

    for key, cols in csv_checks.items():
        if not csv_is_usable(paths[key], required_columns=cols):
            return False

    if not paths["rttm"].exists() or paths["rttm"].stat().st_size == 0:
        return False

    return True


def remove_bad_audio_outputs(paths: dict):
    """
    Si hay restos corruptos de una ejecución anterior, los borra para que el audio se procese limpio.
    """
    for local_path in paths.values():
        if local_path.exists():
            try:
                if local_path.stat().st_size == 0:
                    local_path.unlink()
            except Exception:
                pass


def try_restore_audio_outputs_from_gcs(paths: dict):
    restored_any = False

    for local_path in paths.values():
        if not local_path.exists() or local_path.stat().st_size == 0:
            restored = download_file_from_gcs_if_exists(local_path, GCS_DIARIZATION_OUTPUT_PREFIX)
            restored_any = restored or restored_any

    return restored_any


def upload_audio_outputs_to_gcs(paths: dict):
    for local_path in paths.values():
        upload_file_to_gcs(local_path, GCS_DIARIZATION_OUTPUT_PREFIX)


def build_summary_row_from_outputs(audio_path: Path, paths: dict, mode: str):
    df_regular = read_csv_robust(paths["regular"], columns=DIARIZATION_SEGMENT_COLUMNS)
    df_scored = read_csv_robust(paths["scored"], columns=SCORED_SEGMENT_COLUMNS)
    df_valid = read_csv_robust(paths["valid"], columns=SCORED_SEGMENT_COLUMNS)
    df_anchors = read_csv_robust(paths["anchors"], columns=ANCHOR_SEGMENT_COLUMNS)

    if not df_regular.empty:
        overlap_intervals = compute_overlap_intervals(df_regular)
        n_overlap_regions = len(overlap_intervals)
    else:
        n_overlap_regions = 0

    duration_sec = np.nan
    if not df_scored.empty and "end" in df_scored.columns:
        duration_sec = float(df_scored["end"].max())

    n_speakers = (
        df_scored["speaker"].nunique()
        if ("speaker" in df_scored.columns and not df_scored.empty)
        else 0
    )

    return {
        "audio_file": audio_path.name,
        "audio_stem": audio_path.stem,
        "sample_rate": np.nan,
        "duration_sec": duration_sec,
        "diarization_mode": mode,
        "n_regular_segments": len(df_regular),
        "n_scored_segments": len(df_scored),
        "n_valid_segments": len(df_valid),
        "n_anchor_segments": len(df_anchors),
        "n_speakers": n_speakers,
        "n_overlap_regions": n_overlap_regions,
        "regular_csv_path": str(paths["regular"]),
        "raw_csv_path": str(paths["scored"]),
        "clean_csv_path": str(paths["valid"]),
        "anchors_csv_path": str(paths["anchors"]),
        "rttm_path": str(paths["rttm"]),
    }


def rebuild_consolidated_outputs():
    summary_rows = []
    regular_frames = []
    scored_frames = []
    valid_frames = []
    anchor_frames = []

    for audio_path in wav_files:
        paths = get_audio_output_paths(audio_path)

        if not required_outputs_exist(paths):
            continue

        summary_rows.append(build_summary_row_from_outputs(audio_path, paths, mode="from_checkpoint"))

        df_regular = read_csv_robust(paths["regular"], columns=DIARIZATION_SEGMENT_COLUMNS)
        df_scored = read_csv_robust(paths["scored"], columns=SCORED_SEGMENT_COLUMNS)
        df_valid = read_csv_robust(paths["valid"], columns=SCORED_SEGMENT_COLUMNS)
        df_anchors = read_csv_robust(paths["anchors"], columns=ANCHOR_SEGMENT_COLUMNS)

        if not df_regular.empty:
            regular_frames.append(df_regular)
        if not df_scored.empty:
            scored_frames.append(df_scored)
        if not df_valid.empty:
            valid_frames.append(df_valid)
        if not df_anchors.empty:
            anchor_frames.append(df_anchors)

    df_summary_local = pd.DataFrame(summary_rows, columns=SUMMARY_COLUMNS)
    df_all_regular_local = (
        pd.concat(regular_frames, ignore_index=True)
        if regular_frames
        else pd.DataFrame(columns=DIARIZATION_SEGMENT_COLUMNS)
    )
    df_all_scored_local = (
        pd.concat(scored_frames, ignore_index=True)
        if scored_frames
        else pd.DataFrame(columns=SCORED_SEGMENT_COLUMNS)
    )
    df_all_valid_local = (
        pd.concat(valid_frames, ignore_index=True)
        if valid_frames
        else pd.DataFrame(columns=SCORED_SEGMENT_COLUMNS)
    )
    df_all_anchor_local = (
        pd.concat(anchor_frames, ignore_index=True)
        if anchor_frames
        else pd.DataFrame(columns=ANCHOR_SEGMENT_COLUMNS)
    )

    write_csv_atomic(df_summary_local, summary_csv, columns=SUMMARY_COLUMNS)
    write_csv_atomic(df_all_regular_local, all_regular_segments_csv, columns=DIARIZATION_SEGMENT_COLUMNS)
    write_csv_atomic(df_all_scored_local, all_scored_segments_csv, columns=SCORED_SEGMENT_COLUMNS)
    write_csv_atomic(df_all_valid_local, all_valid_segments_csv, columns=SCORED_SEGMENT_COLUMNS)
    write_csv_atomic(df_all_anchor_local, all_anchor_segments_csv, columns=ANCHOR_SEGMENT_COLUMNS)

    for path in [
        summary_csv,
        all_regular_segments_csv,
        all_scored_segments_csv,
        all_valid_segments_csv,
        all_anchor_segments_csv,
    ]:
        upload_file_to_gcs(path, GCS_DIARIZATION_OUTPUT_PREFIX)

    return (
        df_summary_local,
        df_all_regular_local,
        df_all_scored_local,
        df_all_valid_local,
        df_all_anchor_local,
    )


processed_now = 0
skipped_existing = 0
failed_rows = []
total_audios = len(wav_files)

print("Inicio de diarización robusta")
print(f"Total audios: {total_audios}")
print(f"RE_DIARIZAR: {RE_DIARIZAR}")
print(f"BATCH_SAVE_EVERY: {BATCH_SAVE_EVERY}")
print(f"Destino GCS: {GCS_DIARIZATION_OUTPUT_PREFIX}")

for i, audio_path in enumerate(wav_files, start=1):
    paths = get_audio_output_paths(audio_path)

    if (not RE_DIARIZAR) and RESUME_FROM_GCS:
        try_restore_audio_outputs_from_gcs(paths)

    if (not RE_DIARIZAR) and required_outputs_exist(paths):
        skipped_existing += 1
        clear_output(wait=True)
        print(f"[{i}/{total_audios}] Saltando ya procesado: {audio_path.name}")
        print(f"Procesados nuevos: {processed_now} | Reusados: {skipped_existing} | Errores: {len(failed_rows)}")
        continue

    # Si existen restos de CSVs de 0 bytes, se eliminan antes de reprocesar.
    remove_bad_audio_outputs(paths)

    clear_output(wait=True)
    print(f"[{i}/{total_audios}] Diarizando: {audio_path.name}")
    print(f"Procesados nuevos: {processed_now} | Reusados: {skipped_existing} | Errores: {len(failed_rows)}")

    try:
        result = diarize_audio(audio_path, pipeline)

        # Guardado histórico del notebook.
        raw_csv_path, clean_csv_path, anchors_csv_path, rttm_path = save_diarization_outputs(
            audio_path,
            result,
            OUTPUT_DIR,
        )

        # Guardado adicional de la diarización regular para reconstruir overlap/consolidado.
        write_csv_atomic(result["df_regular"], paths["regular"], columns=DIARIZATION_SEGMENT_COLUMNS)

        # Asegurar que paths recoge los nombres reales guardados por save_diarization_outputs.
        paths["scored"] = raw_csv_path
        paths["valid"] = clean_csv_path
        paths["anchors"] = anchors_csv_path
        paths["rttm"] = rttm_path

        if not required_outputs_exist(paths):
            raise RuntimeError("El audio terminó, pero alguno de sus outputs quedó incompleto o ilegible.")

        if UPLOAD_EACH_AUDIO_TO_GCS:
            upload_audio_outputs_to_gcs(paths)

        processed_now += 1

    except Exception as e:
        failed_rows.append({
            "audio_file": audio_path.name,
            "audio_stem": audio_path.stem,
            "error": str(e),
        })
        continue

    # Checkpoint cada N audios nuevos o al final.
    if (processed_now > 0 and processed_now % BATCH_SAVE_EVERY == 0) or (i == total_audios):
        clear_output(wait=True)
        print(f"Checkpoint: reconstruyendo consolidados tras {processed_now} audios nuevos...")
        (
            df_summary,
            df_all_regular_segments,
            df_all_scored_segments,
            df_all_valid_segments,
            df_all_anchor_segments,
        ) = rebuild_consolidated_outputs()
        print("Checkpoint guardado localmente y subido a GCS.")
        print(f"Audios consolidados: {len(df_summary)}")

# Checkpoint final aunque el último batch no haya caído exacto en múltiplo de BATCH_SAVE_EVERY.
(
    df_summary,
    df_all_regular_segments,
    df_all_scored_segments,
    df_all_valid_segments,
    df_all_anchor_segments,
) = rebuild_consolidated_outputs()

if failed_rows:
    df_diarization_errors = pd.DataFrame(failed_rows)
    errors_csv = OUTPUT_DIR / "diarization_errors.csv"
    write_csv_atomic(df_diarization_errors, errors_csv)
    upload_file_to_gcs(errors_csv, GCS_DIARIZATION_OUTPUT_PREFIX)
else:
    df_diarization_errors = pd.DataFrame(columns=["audio_file", "audio_stem", "error"])

print("\nDiarización finalizada o reanudada correctamente.")
print(f"Audios nuevos procesados en esta ejecución: {processed_now}")
print(f"Audios reutilizados desde outputs previos: {skipped_existing}")
print(f"Errores: {len(failed_rows)}")
print("Resumen:", summary_csv)
print("Segmentos regulares:", all_regular_segments_csv)
print("Segmentos puntuados:", all_scored_segments_csv)
print("Segmentos válidos:", all_valid_segments_csv)
print("Anchors:", all_anchor_segments_csv)

df_summary

[1200/1200] Saltando ya procesado: raw_bajas_9157454659260016851_clean.wav
Procesados nuevos: 0 | Reusados: 1198 | Errores: 2

Diarización finalizada o reanudada correctamente.
Audios nuevos procesados en esta ejecución: 0
Audios reutilizados desde outputs previos: 1198
Errores: 2
Resumen: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/diarization_summary.csv
Segmentos regulares: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/diarization_all_regular_segments.csv
Segmentos puntuados: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/diarization_all_scored_segments.csv
Segmentos válidos: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/diarization_all_valid_segments.csv
Anchors: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/diarization_all_anchor_segments.csv

,audio_file,audio_stem,sample_rate,duration_sec,diarization_mode,n_regular_segments,n_scored_segments,n_valid_segments,n_anchor_segments,n_speakers,n_overlap_regions,regular_csv_path,raw_csv_path,clean_csv_path,anchors_csv_path,rttm_path
0,raw_9154117451310006851_clean.wav,raw_9154117451310006851_clean,NaN,171.362844,from_checkpoint,84,67,42,6,2,28,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...
1,raw_9154117551220006851_clean.wav,raw_9154117551220006851_clean,NaN,175.581594,from_checkpoint,79,72,41,6,2,12,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...
2,raw_9154127337680006851_clean.wav,raw_9154127337680006851_clean,NaN,143.519094,from_checkpoint,87,69,36,6,2,26,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...
3,raw_9154142438160016851_clean.wav,raw_9154142438160016851_clean,NaN,265.457844,from_checkpoint,114,79,50,6,2,16,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...
4,raw_9154152155960016851_clean.wav,raw_9154152155960016851_clean,NaN,172.341594,from_checkpoint,103,88,42,6,2,18,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1193,raw_bajas_9157452496450006851_clean.wav,raw_bajas_9157452496450006851_clean,NaN,175.682844,from_checkpoint,39,21,16,6,2,6,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...
1194,raw_bajas_9157452583930006851_clean.wav,raw_bajas_9157452583930006851_clean,NaN,268.731594,from_checkpoint,122,97,64,6,2,38,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...
1195,raw_bajas_9157452646670006851_clean.wav,raw_bajas_9157452646670006851_clean,NaN,83.882844,from_checkpoint,30,21,17,6,2,3,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...
1196,raw_bajas_9157453715050006851_clean.wav,raw_bajas_9157453715050006851_clean,NaN,160.967844,from_checkpoint,69,52,32,6,2,5,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...
1197,raw_bajas_9157454659260016851_clean.wav,raw_bajas_9157454659260016851_clean,NaN,195.156594,from_checkpoint,62,40,30,6,2,9,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...

In [11]:
# Vista rápida del consolidado

print("Total de audios procesados:", len(df_summary))
print("Total de segmentos puntuados:", len(df_all_scored_segments))
print("Total de segmentos válidos:", len(df_all_valid_segments))
print("Total de anchors:", len(df_all_anchor_segments))

df_summary[[
    "audio_file",
    "duration_sec",
    "n_regular_segments",
    "n_scored_segments",
    "n_valid_segments",
    "n_anchor_segments",
    "n_overlap_regions",
    "n_speakers"
]]

Total de audios procesados: 1198
Total de segmentos puntuados: 73000
Total de segmentos válidos: 43867
Total de anchors: 7038

,audio_file,duration_sec,n_regular_segments,n_scored_segments,n_valid_segments,n_anchor_segments,n_overlap_regions,n_speakers
0,raw_9154117451310006851_clean.wav,171.362844,84,67,42,6,28,2
1,raw_9154117551220006851_clean.wav,175.581594,79,72,41,6,12,2
2,raw_9154127337680006851_clean.wav,143.519094,87,69,36,6,26,2
3,raw_9154142438160016851_clean.wav,265.457844,114,79,50,6,16,2
4,raw_9154152155960016851_clean.wav,172.341594,103,88,42,6,18,2
...,...,...,...,...,...,...,...,...
1193,raw_bajas_9157452496450006851_clean.wav,175.682844,39,21,16,6,6,2
1194,raw_bajas_9157452583930006851_clean.wav,268.731594,122,97,64,6,38,2
1195,raw_bajas_9157452646670006851_clean.wav,83.882844,30,21,17,6,3,2
1196,raw_bajas_9157453715050006851_clean.wav,160.967844,69,52,32,6,5,2
1197,raw_bajas_9157454659260016851_clean.wav,195.156594,62,40,30,6,9,2

In [12]:
# =========================
# CONFIGURACIÓN DE SALIDA DE DIARIZACIÓN EN GCS
# =========================

from google.cloud import storage
from IPython.display import clear_output

GCS_DIARIZATION_OUTPUT_PREFIX = "gs://catedras_audio_detection/pipelineA/procesados_UNAV/diarization_outputs/"

In [13]:
# =========================
# SUBIDA DE OUTPUTS DE DIARIZACIÓN A GCS
# =========================

UPLOAD_OUTPUTS_TO_GCS = RE_DIARIZAR

def split_gcs_uri(gcs_uri: str):
    if not gcs_uri.startswith("gs://"):
        raise ValueError("La ruta debe empezar por 'gs://'")
    path = gcs_uri[5:]
    bucket_name, _, prefix = path.partition("/")
    return bucket_name, prefix


def upload_directory_to_gcs(local_dir: Path, gcs_prefix: str):
    gcs_client = storage.Client()
    bucket_name, prefix = split_gcs_uri(gcs_prefix)
    bucket = gcs_client.bucket(bucket_name)

    files_to_upload = [p for p in local_dir.rglob("*") if p.is_file()]
    total_files = len(files_to_upload)

    for i, local_path in enumerate(files_to_upload, start=1):
        relative_path = local_path.relative_to(local_dir).as_posix()
        blob_path = f"{prefix}{relative_path}"

        clear_output(wait=True)
        print(f"Subiendo outputs {i}/{total_files}: {relative_path}")

        blob = bucket.blob(blob_path)
        blob.upload_from_filename(str(local_path))

    clear_output(wait=True)
    print(f"Subida completada: {total_files} archivos")
    print(f"Destino: {gcs_prefix}")


if UPLOAD_OUTPUTS_TO_GCS:
    upload_directory_to_gcs(
        local_dir=OUTPUT_DIR,
        gcs_prefix=GCS_DIARIZATION_OUTPUT_PREFIX
    )
else:
    print("Subida a GCS omitida porque no se generaron nuevos outputs.")

Subida a GCS omitida porque no se generaron nuevos outputs.

# ANALISIS POSTERIOR

In [14]:
# Seleccionar aleatoriamente audios para auditoría manual

n_to_sample = min(N_AUDIT, len(wav_files))
random.seed(RANDOM_SEED)

audit_files = random.sample(wav_files, k=n_to_sample)

print(f"Audios seleccionados aleatoriamente para auditoría: {len(audit_files)}")
for path in audit_files:
    print("-", path.name)

Audios seleccionados aleatoriamente para auditoría: 5
- raw_bajas_9156058984840006851_clean.wav
- raw_9154814911390016851_clean.wav
- raw_bajas_9156641114290006851_clean.wav
- raw_bajas_9156546642290006851_clean.wav
- raw_bajas_9156492258420006851_clean.wav

In [15]:
# Exportar segmentos SOLO para la muestra aleatoria de auditoría

audit_export_rows = []

for audio_path in audit_files:
    clean_csv_path = OUTPUT_DIR / f"{audio_path.stem}.csv"
    result = export_segments_from_csv(audio_path, clean_csv_path, SEGMENTS_DIR)
    result["export_type"] = "valid_segments"
    audit_export_rows.append(result)

    if EXPORT_ANCHORS_FOR_AUDIT:
        anchors_csv_path = OUTPUT_DIR / f"{audio_path.stem}_anchors.csv"
        result_anchor = export_segments_from_csv(audio_path, anchors_csv_path, ANCHOR_SEGMENTS_DIR)
        result_anchor["export_type"] = "anchors"
        audit_export_rows.append(result_anchor)

df_audit_exports = pd.DataFrame(audit_export_rows)

print("Exportación de segmentos completada")
df_audit_exports

Exportación de segmentos completada

,audio_file,segments_folder,segments_exported,export_type
0,raw_bajas_9156058984840006851_clean.wav,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,38,valid_segments
1,raw_bajas_9156058984840006851_clean.wav,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,6,anchors
2,raw_9154814911390016851_clean.wav,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,47,valid_segments
3,raw_9154814911390016851_clean.wav,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,6,anchors
4,raw_bajas_9156641114290006851_clean.wav,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,44,valid_segments
5,raw_bajas_9156641114290006851_clean.wav,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,6,anchors
6,raw_bajas_9156546642290006851_clean.wav,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,45,valid_segments
7,raw_bajas_9156546642290006851_clean.wav,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,6,anchors
8,raw_bajas_9156492258420006851_clean.wav,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,25,valid_segments
9,raw_bajas_9156492258420006851_clean.wav,/home/jupyter/TFM_ProcesadoDeAudios/data/diari...,6,anchors

In [16]:
# Modelo de embeddings

import torchaudio
from pyannote.audio.pipelines.speaker_verification import PretrainedSpeakerEmbedding

# Salidas de la etapa final
FINAL_RELABEL_DIR = OUTPUT_DIR / "final_relabel"
FINAL_RELABEL_DIR.mkdir(parents=True, exist_ok=True)

# Guardado adicional de embeddings vectoriales para auditoría/demo.
# No modifica los CSVs principales del pipeline; crea CSVs separados con columnas emb_0000, emb_0001, ...
SAVE_EMBEDDING_VECTOR_CSVS = True
EMBEDDING_VECTOR_CSV_DIR = FINAL_RELABEL_DIR / "embedding_vectors_csv"
EMBEDDING_VECTOR_CSV_DIR.mkdir(parents=True, exist_ok=True)

# Modelo para convertir voz -> embedding
EMBEDDING_MODEL_ID = "pyannote/wespeaker-voxceleb-resnet34-LM"

# El modelo espera 16 kHz
EMBEDDING_SAMPLE_RATE = 16000

# Si la ventaja entre el mejor speaker y el segundo es muy pequeña,
# dejamos el speaker original para no sobrecorregir
RELABEL_MIN_MARGIN = 0.01

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Cargar una sola vez
embedding_model = PretrainedSpeakerEmbedding(
    EMBEDDING_MODEL_ID,
    device=device,
    token=HF_TOKEN
)

print("Embedding model cargado:", EMBEDDING_MODEL_ID)
print("Device:", device)
print("Sample rate esperado:", EMBEDDING_SAMPLE_RATE)
print("RELABEL_MIN_MARGIN:", RELABEL_MIN_MARGIN)

Embedding model cargado: pyannote/wespeaker-voxceleb-resnet34-LM
Device: cpu
Sample rate esperado: 16000
RELABEL_MIN_MARGIN: 0.01

In [17]:
# Funciones auxiliares para relabeling con embeddings

def l2_normalize(vec: np.ndarray):
    # Pasar a float32 y a vector 1D
    vec = np.asarray(vec, dtype=np.float32).reshape(-1)

    # Norma L2
    norm = np.linalg.norm(vec)

    # Evitar dividir entre cero
    if norm <= 1e-12:
        return vec

    return vec / norm


def cosine_distance(vec_a: np.ndarray, vec_b: np.ndarray):
    # Distancia coseno = 1 - similitud coseno
    vec_a = l2_normalize(vec_a)
    vec_b = l2_normalize(vec_b)
    return float(1.0 - np.dot(vec_a, vec_b))


def get_segment_waveform_for_embedding(audio_mono, sr: int, start: float, end: float):
    # Tiempo -> muestra
    start_sample = max(0, int(round(start * sr)))
    end_sample = min(len(audio_mono), int(round(end * sr)))

    # Si el tramo queda vacío, no sirve
    if end_sample <= start_sample:
        return None

    # Cortar el segmento exacto
    segment_audio = audio_mono[start_sample:end_sample]

    # Formato esperado: (batch, channel, time)
    waveform = torch.from_numpy(segment_audio).float().unsqueeze(0).unsqueeze(0)

    # Reamostrar si hace falta
    if sr != EMBEDDING_SAMPLE_RATE:
        waveform = torchaudio.functional.resample(waveform, sr, EMBEDDING_SAMPLE_RATE)

    return waveform


def get_segment_embedding(audio_mono, sr: int, start: float, end: float):
    # Cortar el waveform del segmento
    waveform = get_segment_waveform_for_embedding(audio_mono, sr, start, end)

    # Si no hay waveform útil, no hay embedding
    if waveform is None or waveform.shape[-1] == 0:
        return None

    # Sacar embedding
    embedding = embedding_model(waveform)

    # Pasar a numpy 1D
    embedding = np.asarray(embedding).reshape(-1)

    # Si sale algo raro, descartar
    if not np.all(np.isfinite(embedding)):
        return None

    # Normalizar para comparar con coseno
    return l2_normalize(embedding)



def embedding_dataframe_to_wide(df_emb: pd.DataFrame, embedding_col: str = "embedding"):
    """
    Convierte una columna de embeddings tipo array en columnas emb_0000, emb_0001, ...
    para poder guardar los vectores en CSV sin alterar los CSVs principales.
    """
    if df_emb is None or df_emb.empty or embedding_col not in df_emb.columns:
        return pd.DataFrame()

    df_valid = df_emb[df_emb[embedding_col].notna()].copy()
    if df_valid.empty:
        return pd.DataFrame()

    emb_matrix = np.vstack(df_valid[embedding_col].to_list()).astype(np.float32)
    emb_cols = [f"emb_{i:04d}" for i in range(emb_matrix.shape[1])]

    df_meta = df_valid.drop(columns=[embedding_col]).reset_index(drop=True)
    df_vectors = pd.DataFrame(emb_matrix, columns=emb_cols)

    return pd.concat([df_meta, df_vectors], axis=1)


def write_embedding_vectors_csv(df_emb: pd.DataFrame, output_path: Path, embedding_col: str = "embedding"):
    """
    Guarda embeddings vectoriales en CSV ancho.
    Devuelve el DataFrame ancho para poder consolidarlo después.
    """
    if not globals().get("SAVE_EMBEDDING_VECTOR_CSVS", False):
        return pd.DataFrame()

    df_wide = embedding_dataframe_to_wide(df_emb, embedding_col=embedding_col)
    if df_wide.empty:
        return df_wide

    output_path.parent.mkdir(parents=True, exist_ok=True)
    write_csv_atomic(df_wide, output_path)
    return df_wide


def build_anchor_centroids(df_anchors: pd.DataFrame, audio_mono, sr: int):
    # Cada anchor -> 1 embedding
    # Varios anchors del mismo speaker -> promedio = centroide

    if df_anchors.empty:
        return pd.DataFrame(), {}

    anchor_rows = []

    for _, row in df_anchors.iterrows():
        emb = get_segment_embedding(
            audio_mono=audio_mono,
            sr=sr,
            start=float(row["start"]),
            end=float(row["end"])
        )

        # Si no salió embedding, omitir anchor
        if emb is None:
            continue

        out = row.to_dict()
        out["embedding"] = emb
        anchor_rows.append(out)

    if not anchor_rows:
        return pd.DataFrame(), {}

    df_anchor_emb = pd.DataFrame(anchor_rows)
    centroids = {}

    for speaker, group in df_anchor_emb.groupby("speaker"):
        emb_stack = np.stack(group["embedding"].to_list(), axis=0)
        centroid = np.mean(emb_stack, axis=0)
        centroids[speaker] = l2_normalize(centroid)

    return df_anchor_emb, centroids


def relabel_valid_segments_with_centroids(df_valid: pd.DataFrame, centroids: dict, audio_mono, sr: int):
    # Para cada segmento válido:
    # 1) sacar embedding
    # 2) medir distancia a cada centroide
    # 3) quedarse con el más cercano
    # 4) guardar, en paralelo, los embeddings vectoriales para auditoría/demo

    if df_valid.empty:
        return df_valid.copy(), pd.DataFrame()

    centroid_speakers = sorted(centroids.keys())
    rows = []
    segment_embedding_rows = []

    for _, row in df_valid.iterrows():
        speaker_original = row["speaker"]

        emb = get_segment_embedding(
            audio_mono=audio_mono,
            sr=sr,
            start=float(row["start"]),
            end=float(row["end"])
        )

        out = row.to_dict()
        out["speaker_original"] = speaker_original

        # Si no se pudo sacar embedding, dejar speaker original
        if emb is None:
            out["speaker_final"] = speaker_original
            out["relabel_source"] = "original_no_embedding"
            out["best_distance"] = np.nan
            out["second_distance"] = np.nan
            out["distance_margin"] = np.nan

            for spk in centroid_speakers:
                out[f"dist_{spk}"] = np.nan

            rows.append(out)
            continue

        # Distancia del segmento a cada speaker
        dist_map = {
            spk: cosine_distance(emb, centroid)
            for spk, centroid in centroids.items()
        }

        ordered = sorted(dist_map.items(), key=lambda x: x[1])
        best_speaker, best_distance = ordered[0]

        if len(ordered) > 1:
            second_distance = ordered[1][1]
            distance_margin = second_distance - best_distance
        else:
            second_distance = np.nan
            distance_margin = np.nan

        # Solo cambiar si hay ventaja suficiente
        if np.isnan(distance_margin) or distance_margin >= RELABEL_MIN_MARGIN:
            speaker_final = best_speaker
            relabel_source = "centroid"
        else:
            speaker_final = speaker_original
            relabel_source = "original_low_margin"

        out["speaker_final"] = speaker_final
        out["relabel_source"] = relabel_source
        out["best_distance"] = float(best_distance)
        out["second_distance"] = float(second_distance) if np.isfinite(second_distance) else np.nan
        out["distance_margin"] = float(distance_margin) if np.isfinite(distance_margin) else np.nan

        for spk in centroid_speakers:
            out[f"dist_{spk}"] = float(dist_map[spk])

        emb_out = out.copy()
        emb_out["embedding"] = emb
        segment_embedding_rows.append(emb_out)

        rows.append(out)

    df_relabel = pd.DataFrame(rows).sort_values(["segment_id_raw"]).reset_index(drop=True)

    if segment_embedding_rows:
        df_segment_emb = pd.DataFrame(segment_embedding_rows).sort_values(["segment_id_raw"]).reset_index(drop=True)
    else:
        df_segment_emb = pd.DataFrame()

    return df_relabel, df_segment_emb


def merge_adjacent_same_final_speaker(df_segments: pd.DataFrame, max_gap_sec: float):
    # Merge final después del relabeling

    if df_segments.empty:
        return df_segments.copy()

    df = df_segments.sort_values(["start", "end"]).reset_index(drop=True)
    merged_rows = []

    current = df.iloc[0].to_dict()
    current["merged_n_segments"] = 1
    current["segment_ids_raw"] = [int(current["segment_id_raw"])] if pd.notna(current.get("segment_id_raw")) else []

    for _, row in df.iloc[1:].iterrows():
        gap = float(row["start"]) - float(current["end"])
        same_speaker = row["speaker_final"] == current["speaker_final"]

        # Si es el mismo speaker final y la pausa es corta, unir
        if same_speaker and gap <= max_gap_sec:
            current["end"] = max(float(current["end"]), float(row["end"]))
            current["duration"] = float(current["end"] - current["start"])
            current["merged_n_segments"] += 1

            if pd.notna(row.get("segment_id_raw")):
                current["segment_ids_raw"].append(int(row["segment_id_raw"]))
        else:
            current["segment_ids_raw"] = ",".join(str(x) for x in current["segment_ids_raw"])
            merged_rows.append(current.copy())

            current = row.to_dict()
            current["merged_n_segments"] = 1
            current["segment_ids_raw"] = [int(current["segment_id_raw"])] if pd.notna(current.get("segment_id_raw")) else []

    current["segment_ids_raw"] = ",".join(str(x) for x in current["segment_ids_raw"])
    merged_rows.append(current.copy())

    df_merged = pd.DataFrame(merged_rows).sort_values(["start", "end"]).reset_index(drop=True)
    return df_merged

In [18]:
# Relabeling final por audio

relabel_summary_rows = []
all_final_segment_rows = []
all_final_merged_rows = []
all_anchor_embedding_rows = []
all_changed_rows = []
all_anchor_embedding_vector_rows = []
all_segment_embedding_vector_rows = []

for i, audio_path in enumerate(wav_files, start=1):
    print(f"[{i}/{len(wav_files)}] Relabeling con centroides: {audio_path.name}")

    # Archivos que ya generó la etapa anterior
    valid_csv_path = OUTPUT_DIR / f"{audio_path.stem}.csv"
    anchors_csv_path = OUTPUT_DIR / f"{audio_path.stem}_anchors.csv"

    if not valid_csv_path.exists():
        print("   -> no existe CSV válido, se omite")
        continue

    if not anchors_csv_path.exists():
        print("   -> no existe CSV de anchors, se omite")
        continue

    # Leer valid y anchors de forma robusta. Pueden tener 0 filas, pero deben tener columnas.
    df_valid = read_csv_robust(valid_csv_path, columns=SCORED_SEGMENT_COLUMNS)
    df_anchors = read_csv_robust(anchors_csv_path, columns=ANCHOR_SEGMENT_COLUMNS)

    # Volver a cargar el audio completo
    waveform_mono, audio_mono, sr, duration_sec = load_audio_as_mono(audio_path)

    # 1) Sacar embeddings de anchors
    df_anchor_emb, centroids = build_anchor_centroids(df_anchors, audio_mono, sr)

    n_anchor_embeddings = len(df_anchor_emb)
    n_anchor_speakers = len(centroids)

    # Guardar tabla de anchors que sí lograron embedding
    if not df_anchor_emb.empty:
        tmp_anchor = df_anchor_emb.drop(columns=["embedding"]).copy()
        tmp_anchor["audio_file"] = audio_path.name
        all_anchor_embedding_rows.append(tmp_anchor)

        # CSV adicional con el vector completo del embedding de cada anchor
        df_anchor_emb_for_vectors = df_anchor_emb.copy()
        df_anchor_emb_for_vectors["audio_file"] = audio_path.name
        anchor_embeddings_vectors_csv = EMBEDDING_VECTOR_CSV_DIR / f"{audio_path.stem}_anchor_embeddings_vectors.csv"
        df_anchor_vectors = write_embedding_vectors_csv(
            df_anchor_emb_for_vectors,
            anchor_embeddings_vectors_csv
        )
        if not df_anchor_vectors.empty:
            all_anchor_embedding_vector_rows.append(df_anchor_vectors)

    # Necesitamos 2 centroides para comparar de verdad
    if n_anchor_speakers < 2:
        relabel_summary_rows.append({
            "audio_file": audio_path.name,
            "duration_sec": duration_sec,
            "n_valid_in": len(df_valid),
            "n_anchor_in": len(df_anchors),
            "n_anchor_embeddings": n_anchor_embeddings,
            "n_anchor_speakers": n_anchor_speakers,
            "n_changed_segments": 0,
            "n_final_segments": len(df_valid),
            "n_final_merged_segments": np.nan,
            "mean_distance_margin": np.nan,
            "status": "skipped_not_enough_anchor_speakers"
        })
        print("   -> omitido: no hay anchors suficientes para los dos speakers")
        continue

    # 2) Reetiquetar cada segmento válido
    df_final_segments, df_segment_emb = relabel_valid_segments_with_centroids(
        df_valid=df_valid,
        centroids=centroids,
        audio_mono=audio_mono,
        sr=sr
    )

    # CSV adicional con el vector completo del embedding de cada segmento válido
    if not df_segment_emb.empty:
        df_segment_emb_for_vectors = df_segment_emb.copy()
        df_segment_emb_for_vectors["audio_file"] = audio_path.name
        segment_embeddings_vectors_csv = EMBEDDING_VECTOR_CSV_DIR / f"{audio_path.stem}_segment_embeddings_vectors.csv"
        df_segment_vectors = write_embedding_vectors_csv(
            df_segment_emb_for_vectors,
            segment_embeddings_vectors_csv
        )
        if not df_segment_vectors.empty:
            all_segment_embedding_vector_rows.append(df_segment_vectors)

    # 3) Merge final ya con speaker_final
    df_final_merged = merge_adjacent_same_final_speaker(
        df_segments=df_final_segments,
        max_gap_sec=MAX_GAP_MERGE_SEC
    )

    # 4) Segmentos que sí cambiaron
    df_changed = df_final_segments[
        df_final_segments["speaker_final"] != df_final_segments["speaker_original"]
    ].copy()

    # 5) Guardar salidas por audio
    final_segments_csv = FINAL_RELABEL_DIR / f"{audio_path.stem}_final_segments.csv"
    final_merged_csv = FINAL_RELABEL_DIR / f"{audio_path.stem}_final_merged.csv"
    anchor_embeddings_csv = FINAL_RELABEL_DIR / f"{audio_path.stem}_anchor_embeddings.csv"
    changed_csv = FINAL_RELABEL_DIR / f"{audio_path.stem}_changed_segments.csv"

    df_final_segments.to_csv(final_segments_csv, index=False)
    df_final_merged.to_csv(final_merged_csv, index=False)
    df_changed.to_csv(changed_csv, index=False)

    if not df_anchor_emb.empty:
        df_anchor_emb.drop(columns=["embedding"]).to_csv(anchor_embeddings_csv, index=False)

    # 6) Métricas de resumen
    n_changed_segments = int(len(df_changed))
    mean_distance_margin = (
        float(df_final_segments["distance_margin"].dropna().mean())
        if df_final_segments["distance_margin"].notna().any()
        else np.nan
    )

    relabel_summary_rows.append({
        "audio_file": audio_path.name,
        "duration_sec": duration_sec,
        "n_valid_in": len(df_valid),
        "n_anchor_in": len(df_anchors),
        "n_anchor_embeddings": n_anchor_embeddings,
        "n_anchor_speakers": n_anchor_speakers,
        "n_changed_segments": n_changed_segments,
        "n_final_segments": len(df_final_segments),
        "n_final_merged_segments": len(df_final_merged),
        "mean_distance_margin": mean_distance_margin,
        "final_segments_csv": str(final_segments_csv),
        "final_merged_csv": str(final_merged_csv),
        "anchor_embeddings_csv": str(anchor_embeddings_csv),
        "changed_csv": str(changed_csv),
        "status": "ok"
    })

    all_final_segment_rows.append(df_final_segments.assign(audio_file=audio_path.name))
    all_final_merged_rows.append(df_final_merged.assign(audio_file=audio_path.name))
    all_changed_rows.append(df_changed.assign(audio_file=audio_path.name))

    print(f"   -> segments changed: {n_changed_segments}")
    print(f"   -> final merged segments: {len(df_final_merged)}")

[1/1200] Relabeling con centroides: raw_9154117451310006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 37
[2/1200] Relabeling con centroides: raw_9154117551220006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 41
[3/1200] Relabeling con centroides: raw_9154127337680006851_clean.wav
   -> segments changed: 7
   -> final merged segments: 27
[4/1200] Relabeling con centroides: raw_9154142438160016851_clean.wav
   -> segments changed: 3
   -> final merged segments: 46
[5/1200] Relabeling con centroides: raw_9154152155960016851_clean.wav
   -> segments changed: 3
   -> final merged segments: 38
[6/1200] Relabeling con centroides: raw_9154188548830006851_clean.wav
   -> segments changed: 6
   -> final merged segments: 23
[7/1200] Relabeling con centroides: raw_9154202560160006851_clean.wav
   -> segments changed: 7
   -> final merged segments: 19
[8/1200] Relabeling con centroides: raw_9154202749900006851_clean.wav
   -> segments changed: 11
   -> final merged segments: 30
[9/1200] Relabeling con centroides: raw_9154219744450006851_clean.wav
   -> segments changed: 4
   -> final merged segments: 43
[10/1200] Relabeling con centroides: raw_9154222339820016851_clean.wav
   -> segments changed: 6
   -> final merged segments: 50
[11/1200] Relabeling con centroides: raw_9154281474720016851_clean.wav
   -> segments changed: 1
   -> final merged segments: 38
[12/1200] Relabeling con centroides: raw_9154281641250016851_clean.wav
   -> segments changed: 1
   -> final merged segments: 11
[13/1200] Relabeling con centroides: raw_9154291167650006851_clean.wav
   -> segments changed: 8
   -> final merged segments: 45
[14/1200] Relabeling con centroides: raw_9154334371160016851_clean.wav
   -> segments changed: 4
   -> final merged segments: 55
[15/1200] Relabeling con centroides: raw_9154334697630006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 42
[16/1200] Relabeling con centroides: raw_9154340242110006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 45
[17/1200] Relabeling con centroides: raw_9154340804290006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 21
[18/1200] Relabeling con centroides: raw_9154345341640006851_clean.wav
   -> segments changed: 3
   -> final merged segments: 28
[19/1200] Relabeling con centroides: raw_9154369709820006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 53
[20/1200] Relabeling con centroides: raw_9154377635160016851_clean.wav
   -> segments changed: 11
   -> final merged segments: 43
[21/1200] Relabeling con centroides: raw_9154378200890006851_clean.wav
   -> segments changed: 7
   -> final merged segments: 27
[22/1200] Relabeling con centroides: raw_9154385177500006851_clean.wav
   -> segments changed: 6
   -> final merged segments: 58
[23/1200] Relabeling con centroides: raw_9154387041600016851_clean.wav
   -> segments changed: 4
   -> final merged segments: 24
[24/1200] Relabeling con centroides: raw_9154393370240006851_clean.wav
   -> segments changed: 4
   -> final merged segments: 41
[25/1200] Relabeling con centroides: raw_9154394927400006851_clean.wav
   -> segments changed: 19
   -> final merged segments: 66
[26/1200] Relabeling con centroides: raw_9154401071060016851_clean.wav
   -> segments changed: 4
   -> final merged segments: 17
[27/1200] Relabeling con centroides: raw_9154401454010016851_clean.wav
   -> segments changed: 2
   -> final merged segments: 41
[28/1200] Relabeling con centroides: raw_9154436006430006851_clean.wav
   -> segments changed: 6
   -> final merged segments: 18
[29/1200] Relabeling con centroides: raw_9154438077400006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 28
[30/1200] Relabeling con centroides: raw_9154438220380006851_clean.wav
   -> segments changed: 3
   -> final merged segments: 29
[31/1200] Relabeling con centroides: raw_9154487929260056851_clean.wav
   -> segments changed: 4
   -> final merged segments: 61
[32/1200] Relabeling con centroides: raw_9154498284840036851_clean.wav
   -> segments changed: 1
   -> final merged segments: 51
[33/1200] Relabeling con centroides: raw_9154521617620006851_clean.wav
   -> segments changed: 8
   -> final merged segments: 39
[34/1200] Relabeling con centroides: raw_9154523187440006851_clean.wav
   -> omitido: no hay anchors suficientes para los dos speakers
[35/1200] Relabeling con centroides: raw_9154524262530006851_clean.wav
   -> segments changed: 3
   -> final merged segments: 48
[36/1200] Relabeling con centroides: raw_9154530420310006851_clean.wav
   -> segments changed: 5
   -> final merged segments: 40
[37/1200] Relabeling con centroides: raw_9154538337930006851_clean.wav
   -> segments changed: 7
   -> final merged segments: 32
[38/1200] Relabeling con centroides: raw_9154539888000006851_clean.wav
   -> segments changed: 3
   -> final merged segments: 64
[39/1200] Relabeling con centroides: raw_9154565956690016851_clean.wav
   -> segments changed: 1
   -> final merged segments: 30
[40/1200] Relabeling con centroides: raw_9154566011940006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 37
[41/1200] Relabeling con centroides: raw_9154616263500006851_clean.wav
   -> segments changed: 11
   -> final merged segments: 34
[42/1200] Relabeling con centroides: raw_9154634924590006851_clean.wav
   -> omitido: no hay anchors suficientes para los dos speakers
[43/1200] Relabeling con centroides: raw_9154635155880006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 13
[44/1200] Relabeling con centroides: raw_9154642005220006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 33
[45/1200] Relabeling con centroides: raw_9154654032600006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 34
[46/1200] Relabeling con centroides: raw_9154689192230016851_clean.wav
   -> segments changed: 2
   -> final merged segments: 46
[47/1200] Relabeling con centroides: raw_9154713675550006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 30
[48/1200] Relabeling con centroides: raw_9154728716220016851_clean.wav
   -> segments changed: 10
   -> final merged segments: 23
[49/1200] Relabeling con centroides: raw_9154801333870006851_clean.wav
   -> segments changed: 4
   -> final merged segments: 54
[50/1200] Relabeling con centroides: raw_9154808626360006851_clean.wav
   -> segments changed: 5
   -> final merged segments: 38
[51/1200] Relabeling con centroides: raw_9154808735260016851_clean.wav
   -> segments changed: 3
   -> final merged segments: 47
[52/1200] Relabeling con centroides: raw_9154814911390016851_clean.wav
   -> segments changed: 10
   -> final merged segments: 43
[53/1200] Relabeling con centroides: raw_9154817984460016851_clean.wav
   -> segments changed: 4
   -> final merged segments: 40
[54/1200] Relabeling con centroides: raw_9154823963540016851_clean.wav
   -> segments changed: 2
   -> final merged segments: 26
[55/1200] Relabeling con centroides: raw_9154825192820016851_clean.wav
   -> segments changed: 2
   -> final merged segments: 24
[56/1200] Relabeling con centroides: raw_9154849440580026851_clean.wav
   -> segments changed: 0
   -> final merged segments: 37
[57/1200] Relabeling con centroides: raw_9154850728290006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 20
[58/1200] Relabeling con centroides: raw_9154851543210006851_clean.wav
   -> segments changed: 6
   -> final merged segments: 27
[59/1200] Relabeling con centroides: raw_9154885552000026851_clean.wav
   -> segments changed: 6
   -> final merged segments: 23
[60/1200] Relabeling con centroides: raw_9154939063420006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 32
[61/1200] Relabeling con centroides: raw_9154944370730026851_clean.wav
   -> segments changed: 5
   -> final merged segments: 25
[62/1200] Relabeling con centroides: raw_9155014588640006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 23
[63/1200] Relabeling con centroides: raw_9155034827250016851_clean.wav
   -> segments changed: 4
   -> final merged segments: 38
[64/1200] Relabeling con centroides: raw_9155050436480006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 28
[65/1200] Relabeling con centroides: raw_9155057330550016851_clean.wav
   -> segments changed: 1
   -> final merged segments: 53
[66/1200] Relabeling con centroides: raw_9155065404680016851_clean.wav
   -> segments changed: 13
   -> final merged segments: 42
[67/1200] Relabeling con centroides: raw_9155065429200036851_clean.wav
   -> segments changed: 6
   -> final merged segments: 25
[68/1200] Relabeling con centroides: raw_9155074905640006851_clean.wav
   -> segments changed: 4
   -> final merged segments: 32
[69/1200] Relabeling con centroides: raw_9155087100570006851_clean.wav
   -> segments changed: 4
   -> final merged segments: 42
[70/1200] Relabeling con centroides: raw_9155101148350016851_clean.wav
   -> segments changed: 1
   -> final merged segments: 45
[71/1200] Relabeling con centroides: raw_9155101208730006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 26
[72/1200] Relabeling con centroides: raw_9155152097350016851_clean.wav
   -> segments changed: 0
   -> final merged segments: 49
[73/1200] Relabeling con centroides: raw_9155155462350016851_clean.wav
   -> segments changed: 5
   -> final merged segments: 46
[74/1200] Relabeling con centroides: raw_9155187335360016851_clean.wav
   -> segments changed: 0
   -> final merged segments: 23
[75/1200] Relabeling con centroides: raw_9155264701480006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 31
[76/1200] Relabeling con centroides: raw_9155277266340006851_clean.wav
   -> segments changed: 6
   -> final merged segments: 28
[77/1200] Relabeling con centroides: raw_9155283378650006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 37
[78/1200] Relabeling con centroides: raw_9155309056180016851_clean.wav
   -> segments changed: 5
   -> final merged segments: 29
[79/1200] Relabeling con centroides: raw_9155318330590006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 43
[80/1200] Relabeling con centroides: raw_9155333249330026851_clean.wav
   -> segments changed: 3
   -> final merged segments: 21
[81/1200] Relabeling con centroides: raw_9155343183920006851_clean.wav
   -> segments changed: 5
   -> final merged segments: 43
[82/1200] Relabeling con centroides: raw_9155389881530006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 24
[83/1200] Relabeling con centroides: raw_9155414996490016851_clean.wav
   -> segments changed: 0
   -> final merged segments: 52
[84/1200] Relabeling con centroides: raw_9155421003730006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 22
[85/1200] Relabeling con centroides: raw_9155423381440006851_clean.wav
   -> segments changed: 9
   -> final merged segments: 31
[86/1200] Relabeling con centroides: raw_9155429489310016851_clean.wav
   -> segments changed: 2
   -> final merged segments: 53
[87/1200] Relabeling con centroides: raw_9155464048330006851_clean.wav
   -> segments changed: 11
   -> final merged segments: 41
[88/1200] Relabeling con centroides: raw_9155484466040026851_clean.wav
   -> segments changed: 10
   -> final merged segments: 44
[89/1200] Relabeling con centroides: raw_9155526428000006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 32
[90/1200] Relabeling con centroides: raw_9155532282550016851_clean.wav
   -> segments changed: 3
   -> final merged segments: 25
[91/1200] Relabeling con centroides: raw_9155534788250006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 22
[92/1200] Relabeling con centroides: raw_9155549398410026851_clean.wav
   -> segments changed: 0
   -> final merged segments: 28
[93/1200] Relabeling con centroides: raw_9155577198850006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 18
[94/1200] Relabeling con centroides: raw_9155578970760016851_clean.wav
   -> segments changed: 7
   -> final merged segments: 41
[95/1200] Relabeling con centroides: raw_9155592697680016851_clean.wav
   -> segments changed: 5
   -> final merged segments: 47
[96/1200] Relabeling con centroides: raw_9155637406570016851_clean.wav
   -> segments changed: 2
   -> final merged segments: 37
[97/1200] Relabeling con centroides: raw_9155653780600006851_clean.wav
   -> segments changed: 8
   -> final merged segments: 46
[98/1200] Relabeling con centroides: raw_9155662567460006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 26
[99/1200] Relabeling con centroides: raw_9155673602710006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 43
[100/1200] Relabeling con centroides: raw_9155706734190006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 28
[101/1200] Relabeling con centroides: raw_9155707018060006851_clean.wav
   -> segments changed: 5
   -> final merged segments: 27
[102/1200] Relabeling con centroides: raw_9155714853000006851_clean.wav
   -> segments changed: 8
   -> final merged segments: 21
[103/1200] Relabeling con centroides: raw_9155758669540006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 22
[104/1200] Relabeling con centroides: raw_9155765842720006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 17
[105/1200] Relabeling con centroides: raw_9155774206610016851_clean.wav
   -> segments changed: 2
   -> final merged segments: 41
[106/1200] Relabeling con centroides: raw_9155784264530006851_clean.wav
   -> segments changed: 8
   -> final merged segments: 36
[107/1200] Relabeling con centroides: raw_9155784328650016851_clean.wav
   -> segments changed: 0
   -> final merged segments: 31
[108/1200] Relabeling con centroides: raw_9155792856710006851_clean.wav
   -> omitido: no hay anchors suficientes para los dos speakers
[109/1200] Relabeling con centroides: raw_9155793165960006851_clean.wav
   -> segments changed: 9
   -> final merged segments: 33
[110/1200] Relabeling con centroides: raw_9155869610330006851_clean.wav
   -> segments changed: 10
   -> final merged segments: 53
[111/1200] Relabeling con centroides: raw_9155870305570006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 65
[112/1200] Relabeling con centroides: raw_9155880517290006851_clean.wav
   -> segments changed: 3
   -> final merged segments: 22
[113/1200] Relabeling con centroides: raw_9155881319370006851_clean.wav
   -> segments changed: 6
   -> final merged segments: 52
[114/1200] Relabeling con centroides: raw_9155886882520006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 26
[115/1200] Relabeling con centroides: raw_9155895660400006851_clean.wav
   -> segments changed: 3
   -> final merged segments: 40
[116/1200] Relabeling con centroides: raw_9155897411670016851_clean.wav
   -> segments changed: 0
   -> final merged segments: 45
[117/1200] Relabeling con centroides: raw_9155912774070006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 41
[118/1200] Relabeling con centroides: raw_9155916961200006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 26
[119/1200] Relabeling con centroides: raw_9155938668110006851_clean.wav
   -> segments changed: 5
   -> final merged segments: 21
[120/1200] Relabeling con centroides: raw_9155955849600006851_clean.wav
   -> segments changed: 8
   -> final merged segments: 20
[121/1200] Relabeling con centroides: raw_9155959468360006851_clean.wav
   -> segments changed: 5
   -> final merged segments: 46
[122/1200] Relabeling con centroides: raw_9155976538910006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 12
[123/1200] Relabeling con centroides: raw_9155993306570006851_clean.wav
   -> segments changed: 6
   -> final merged segments: 27
[124/1200] Relabeling con centroides: raw_9155994224830006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 25
[125/1200] Relabeling con centroides: raw_9155998683240056851_clean.wav
   -> segments changed: 1
   -> final merged segments: 26
[126/1200] Relabeling con centroides: raw_9155999546750006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 28
[127/1200] Relabeling con centroides: raw_9156009940320026851_clean.wav
   -> segments changed: 5
   -> final merged segments: 29
[128/1200] Relabeling con centroides: raw_9156016321910006851_clean.wav
   -> segments changed: 3
   -> final merged segments: 30
[129/1200] Relabeling con centroides: raw_9156017687900006851_clean.wav
   -> segments changed: 3
   -> final merged segments: 33
[130/1200] Relabeling con centroides: raw_9156026774190026851_clean.wav
   -> segments changed: 10
   -> final merged segments: 25
[131/1200] Relabeling con centroides: raw_9156027267320016851_clean.wav
   -> segments changed: 3
   -> final merged segments: 94
[132/1200] Relabeling con centroides: raw_9156071902100006851_clean.wav
   -> segments changed: 3
   -> final merged segments: 42
[133/1200] Relabeling con centroides: raw_9156077194890016851_clean.wav
   -> segments changed: 7
   -> final merged segments: 57
[134/1200] Relabeling con centroides: raw_9156086415120006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 8
[135/1200] Relabeling con centroides: raw_9156095001490006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 26
[136/1200] Relabeling con centroides: raw_9156095828190006851_clean.wav
   -> segments changed: 5
   -> final merged segments: 26
[137/1200] Relabeling con centroides: raw_9156123880750006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 27
[138/1200] Relabeling con centroides: raw_9156128121440006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 41
[139/1200] Relabeling con centroides: raw_9156131897590006851_clean.wav
   -> segments changed: 2
   -> final merged segments: 33
[140/1200] Relabeling con centroides: raw_9156147739220006851_clean.wav
   -> segments changed: 1
   -> final merged segments: 34
[141/1200] Relabeling con centroides: raw_9156149723090006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 28
[142/1200] Relabeling con centroides: raw_9156156815080016851_clean.wav
   -> omitido: no hay anchors suficientes para los dos speakers
[143/1200] Relabeling con centroides: raw_9156156834480016851_clean.wav
   -> segments changed: 1
   -> final merged segments: 43
[144/1200] Relabeling con centroides: raw_9156156895160026851_clean.wav
   -> segments changed: 14
   -> final merged segments: 29
[145/1200] Relabeling con centroides: raw_9156183597960006851_clean.wav
   -> segments changed: 0
   -> final merged segments: 43
[146/1200] Relabeling con centroides: raw_9156190741830016851_clean.wav
   -> segments changed: 0
   -> final merged segments: 29
[147/1200] Relabeling con centroides: raw_9156190759670016851_clean.wav
   -> segments changed: 4
   -> final merged segments: 38
[148/1200] Relabeling con centroides: raw_9156198408720016851_clean.wav
   -> segments changed: 3
   -> final merged segments: 37
[149/1200] Relabeling con centroides: raw_9156198475400026851_clean.wav
   -> segments changed: 1
   -> final merged segments: 34
[150/1200] Relabeling con centroides: raw_9156216116830016851_clean.wav
   -> segments changed: 3
   -> final merged segments: 42
[151/1200] Relabeling con centroides: raw_9156250432600026851_clean.wav
   -> segments changed: 2
   -> final merged segments: 31
[152/1200] Relabeling con centroides: raw_9156270279010016851_clean.wav
   -> segments changed: 8
   -> final merged segments: 34
[153/1200] Relabeling con centroides: raw_9156275777100006851_clean.wav
   -> segments changed: 10
   -> final merged segments: 22
[154/1200] Relabeling con centroides: raw_9156275816450006851_clean.wav
   -> segments changed: 5
   -> final merged segments: 23

In [19]:
# Consolidar CSVs finales

df_relabel_summary = pd.DataFrame(relabel_summary_rows)

if all_final_segment_rows:
    df_all_final_segments = pd.concat(all_final_segment_rows, ignore_index=True)
else:
    df_all_final_segments = pd.DataFrame()

if all_final_merged_rows:
    df_all_final_merged = pd.concat(all_final_merged_rows, ignore_index=True)
else:
    df_all_final_merged = pd.DataFrame()

if all_anchor_embedding_rows:
    df_all_anchor_embeddings = pd.concat(all_anchor_embedding_rows, ignore_index=True)
else:
    df_all_anchor_embeddings = pd.DataFrame()

if all_changed_rows:
    df_all_changed_segments = pd.concat(all_changed_rows, ignore_index=True)
else:
    df_all_changed_segments = pd.DataFrame()

if all_anchor_embedding_vector_rows:
    df_all_anchor_embedding_vectors = pd.concat(all_anchor_embedding_vector_rows, ignore_index=True)
else:
    df_all_anchor_embedding_vectors = pd.DataFrame()

if all_segment_embedding_vector_rows:
    df_all_segment_embedding_vectors = pd.concat(all_segment_embedding_vector_rows, ignore_index=True)
else:
    df_all_segment_embedding_vectors = pd.DataFrame()

relabel_summary_csv = FINAL_RELABEL_DIR / "relabel_summary.csv"
all_final_segments_csv = FINAL_RELABEL_DIR / "all_final_segments.csv"
all_final_merged_csv = FINAL_RELABEL_DIR / "all_final_merged_segments.csv"
all_anchor_embeddings_csv = FINAL_RELABEL_DIR / "all_anchor_embeddings.csv"
all_changed_segments_csv = FINAL_RELABEL_DIR / "all_changed_segments.csv"
all_anchor_embeddings_vectors_csv = EMBEDDING_VECTOR_CSV_DIR / "all_anchor_embeddings_vectors.csv"
all_segment_embeddings_vectors_csv = EMBEDDING_VECTOR_CSV_DIR / "all_segment_embeddings_vectors.csv"

write_csv_atomic(df_relabel_summary, relabel_summary_csv)
write_csv_atomic(df_all_final_segments, all_final_segments_csv)
write_csv_atomic(df_all_final_merged, all_final_merged_csv)
write_csv_atomic(df_all_anchor_embeddings, all_anchor_embeddings_csv)
write_csv_atomic(df_all_changed_segments, all_changed_segments_csv)

if SAVE_EMBEDDING_VECTOR_CSVS:
    if not df_all_anchor_embedding_vectors.empty:
        write_csv_atomic(df_all_anchor_embedding_vectors, all_anchor_embeddings_vectors_csv)
    if not df_all_segment_embedding_vectors.empty:
        write_csv_atomic(df_all_segment_embedding_vectors, all_segment_embeddings_vectors_csv)

print("\nRelabeling completado")
print("Resumen:", relabel_summary_csv)
print("Final segments:", all_final_segments_csv)
print("Final merged:", all_final_merged_csv)
print("Anchor embeddings:", all_anchor_embeddings_csv)
print("Changed:", all_changed_segments_csv)
if SAVE_EMBEDDING_VECTOR_CSVS:
    print("Anchor embedding vectors CSV:", all_anchor_embeddings_vectors_csv)
    print("Segment embedding vectors CSV:", all_segment_embeddings_vectors_csv)

Relabeling completado
Resumen: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/final_relabel/relabel_summary.csv
Final segments: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/final_relabel/all_final_segments.csv
Final merged: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/final_relabel/all_final_merged_segments.csv
Anchor embeddings: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/final_relabel/all_anchor_embeddings.csv
Changed: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/final_relabel/all_changed_segments.csv
Anchor embedding vectors CSV: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/final_relabel/embedding_vectors_csv/all_anchor_embeddings_vectors.csv
Segment embedding vectors CSV: /home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/final_relabel/embedding_vectors_csv/all_segment_embeddings_vectors.csv

In [20]:
# Resumen rápido

df_relabel_summary[[
    "audio_file",
    "n_valid_in",
    "n_anchor_in",
    "n_anchor_embeddings",
    "n_anchor_speakers",
    "n_changed_segments",
    "n_final_segments",
    "n_final_merged_segments",
    "mean_distance_margin",
    "status"
]]

,audio_file,n_valid_in,n_anchor_in,n_anchor_embeddings,n_anchor_speakers,n_changed_segments,n_final_segments,n_final_merged_segments,mean_distance_margin,status
0,raw_9154117451310006851_clean.wav,42,6,6,2,1,42,37.0,0.426726,ok
1,raw_9154117551220006851_clean.wav,41,6,6,2,0,41,41.0,0.395578,ok
2,raw_9154127337680006851_clean.wav,36,6,6,2,7,36,27.0,0.269856,ok
3,raw_9154142438160016851_clean.wav,50,6,6,2,3,50,46.0,0.460637,ok
4,raw_9154152155960016851_clean.wav,42,6,6,2,3,42,38.0,0.349696,ok
...,...,...,...,...,...,...,...,...,...,...
1195,raw_bajas_9157452496450006851_clean.wav,16,6,6,2,1,16,16.0,0.237892,ok
1196,raw_bajas_9157452583930006851_clean.wav,64,6,6,2,2,64,56.0,0.503840,ok
1197,raw_bajas_9157452646670006851_clean.wav,17,6,6,2,3,17,17.0,0.173947,ok
1198,raw_bajas_9157453715050006851_clean.wav,32,6,6,2,5,32,30.0,0.090324,ok
1199,raw_bajas_9157454659260016851_clean.wav,30,6,6,2,2,30,27.0,0.449590,ok

In [21]:
# Tabla maestra de validación por audio

def build_validation_table(audio_name: str):
    # helper: asegurar id en raw
    def ensure_segment_id_raw_in_raw(df_raw: pd.DataFrame):
        df_raw = df_raw.copy()

        if "segment_id_raw" in df_raw.columns:
            return df_raw

        # Si no existe, crear según el orden actual del raw
        df_raw["segment_id_raw"] = np.arange(1, len(df_raw) + 1)
        return df_raw

    # helper: pegar segment_id_raw desde raw a otra tabla
    def attach_segment_id_from_raw_local(df_raw: pd.DataFrame, df_other: pd.DataFrame):
        df_raw_tmp = df_raw.copy()
        df_other_tmp = df_other.copy()

        # Si ya trae el id, no hacer nada
        if "segment_id_raw" in df_other_tmp.columns:
            return df_other_tmp

        # Redondear para evitar problemas por floats
        for col in ["start", "end"]:
            if col in df_raw_tmp.columns:
                df_raw_tmp[col] = df_raw_tmp[col].round(3)
            if col in df_other_tmp.columns:
                df_other_tmp[col] = df_other_tmp[col].round(3)

        if "duration" in df_raw_tmp.columns and "duration" in df_other_tmp.columns:
            df_raw_tmp["duration"] = df_raw_tmp["duration"].round(3)
            df_other_tmp["duration"] = df_other_tmp["duration"].round(3)
            merge_keys = ["start", "end", "duration", "speaker"]
        else:
            merge_keys = ["start", "end", "speaker"]

        df_raw_ids = df_raw_tmp[merge_keys + ["segment_id_raw"]].drop_duplicates()
        df_out = df_other_tmp.merge(df_raw_ids, on=merge_keys, how="left")
        return df_out

    # Aceptar "audio.wav" o solo "audio"
    audio_name = str(audio_name).strip()

    if audio_name.lower().endswith(".wav"):
        audio_stem = Path(audio_name).stem
        audio_file = audio_name
    else:
        audio_stem = audio_name
        audio_file = f"{audio_stem}.wav"

    # Rutas por audio
    raw_csv_path = OUTPUT_DIR / f"{audio_stem}_raw.csv"
    valid_csv_path = OUTPUT_DIR / f"{audio_stem}.csv"
    anchors_csv_path = OUTPUT_DIR / f"{audio_stem}_anchors.csv"
    final_segments_csv_path = FINAL_RELABEL_DIR / f"{audio_stem}_final_segments.csv"
    final_merged_csv_path = FINAL_RELABEL_DIR / f"{audio_stem}_final_merged.csv"
    changed_csv_path = FINAL_RELABEL_DIR / f"{audio_stem}_changed_segments.csv"

    missing = []
    for p in [raw_csv_path, valid_csv_path, anchors_csv_path, final_segments_csv_path, final_merged_csv_path, changed_csv_path]:
        if not p.exists():
            missing.append(str(p))

    if missing:
        raise FileNotFoundError("Faltan archivos para construir la tabla maestra:\n" + "\n".join(missing))

    # Leer tablas de forma robusta
    df_raw = read_csv_robust(raw_csv_path, columns=SCORED_SEGMENT_COLUMNS)
    df_valid = read_csv_robust(valid_csv_path, columns=SCORED_SEGMENT_COLUMNS)
    df_anchors = read_csv_robust(anchors_csv_path, columns=ANCHOR_SEGMENT_COLUMNS)
    df_final_segments = read_csv_robust(final_segments_csv_path)
    df_final_merged = read_csv_robust(final_merged_csv_path)
    df_changed = read_csv_robust(changed_csv_path)

    # Asegurar segment_id_raw en raw
    df_raw = ensure_segment_id_raw_in_raw(df_raw)

    # Recuperar id en valid y anchors si faltara
    df_valid = attach_segment_id_from_raw_local(df_raw, df_valid)
    df_anchors = attach_segment_id_from_raw_local(df_raw, df_anchors)

    # Base = raw
    df = df_raw.copy()

    rename_map = {
        "speaker": "speaker_raw",
        "start": "start_raw",
        "end": "end_raw",
        "duration": "duration_raw",
        "rms_dbfs": "rms_dbfs_raw",
        "overlap_ratio": "overlap_ratio_raw",
        "valid_export": "valid_export_raw",
        "valid_anchor": "valid_anchor_raw",
        "drop_reasons": "drop_reasons_raw",
        "anchor_reasons": "anchor_reasons_raw",
    }
    rename_map = {k: v for k, v in rename_map.items() if k in df.columns}
    df = df.rename(columns=rename_map)

    if "audio_file" not in df.columns:
        df["audio_file"] = audio_file

    # Marcar si sobrevivió a valid
    df_valid_small = df_valid[["segment_id_raw"]].drop_duplicates().copy()
    df_valid_small["is_valid_segment"] = True
    df = df.merge(df_valid_small, on="segment_id_raw", how="left")
    df["is_valid_segment"] = df["is_valid_segment"].fillna(False)

    # Marcar si fue anchor
    keep_anchor_cols = ["segment_id_raw"]
    for col in ["anchor_rank", "anchor_score", "speaker"]:
        if col in df_anchors.columns:
            keep_anchor_cols.append(col)

    df_anchor_small = df_anchors[keep_anchor_cols].drop_duplicates(subset=["segment_id_raw"]).copy()
    df_anchor_small["is_anchor"] = True

    if "speaker" in df_anchor_small.columns:
        df_anchor_small = df_anchor_small.rename(columns={"speaker": "speaker_anchor"})

    df = df.merge(df_anchor_small, on="segment_id_raw", how="left")
    df["is_anchor"] = df["is_anchor"].fillna(False)

    # Pegar resultado del relabeling
    keep_final_cols = ["segment_id_raw"]
    for col in ["speaker_original", "speaker_final", "relabel_source", "best_distance", "second_distance", "distance_margin"]:
        if col in df_final_segments.columns:
            keep_final_cols.append(col)

    df_final_small = df_final_segments[keep_final_cols].drop_duplicates(subset=["segment_id_raw"]).copy()
    df = df.merge(df_final_small, on="segment_id_raw", how="left")

    # Marcar si cambió
    df["was_reclassified"] = (
        df["speaker_original"].notna() &
        df["speaker_final"].notna() &
        (df["speaker_original"] != df["speaker_final"])
    )

    # Marcar si está en changed
    df_changed_small = df_changed[["segment_id_raw"]].drop_duplicates().copy()
    df_changed_small["is_in_changed_sheet"] = True
    df = df.merge(df_changed_small, on="segment_id_raw", how="left")
    df["is_in_changed_sheet"] = df["is_in_changed_sheet"].fillna(False)

    # Mapear a qué merge_group final pertenece
    merge_map_rows = []
    df_merged_tmp = df_final_merged.copy().reset_index(drop=True)
    df_merged_tmp["merge_group_id"] = df_merged_tmp.index + 1

    for _, row in df_merged_tmp.iterrows():
        ids_str = str(row["segment_ids_raw"]) if "segment_ids_raw" in row else ""

        if not ids_str or ids_str == "nan":
            continue

        ids_list = [int(x.strip()) for x in ids_str.split(",") if str(x).strip() != ""]

        for rid in ids_list:
            merge_map_rows.append({
                "segment_id_raw": rid,
                "merge_group_id": row["merge_group_id"],
                "merge_ids_raw": ids_str,
                "merge_n_segments": row["merged_n_segments"] if "merged_n_segments" in row else np.nan,
                "merge_start": row["start"] if "start" in row else np.nan,
                "merge_end": row["end"] if "end" in row else np.nan,
                "merge_duration": row["duration"] if "duration" in row else np.nan,
                "merge_speaker_final": row["speaker_final"] if "speaker_final" in row else np.nan,
            })

    df_merge_map = pd.DataFrame(merge_map_rows)

    if not df_merge_map.empty:
        df = df.merge(df_merge_map, on="segment_id_raw", how="left")
    else:
        df["merge_group_id"] = np.nan
        df["merge_ids_raw"] = np.nan
        df["merge_n_segments"] = np.nan
        df["merge_start"] = np.nan
        df["merge_end"] = np.nan
        df["merge_duration"] = np.nan
        df["merge_speaker_final"] = np.nan

    df["is_in_final_merge"] = df["merge_group_id"].notna()

    # Orden final = orden raw
    df = df.sort_values("segment_id_raw").reset_index(drop=True)

    return df

In [25]:
# ============================================================
# RESUMEN GENERAL DEL RELABELING + EJEMPLO CON CAMBIOS
# Versión corregida: excluye archivos agregados "all_*"
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

OUTPUT_DIR = Path("/home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs")
FINAL_RELABEL_DIR = OUTPUT_DIR / "final_relabel"

# ------------------------------------------------------------
# 1. Buscar archivos finales disponibles
# ------------------------------------------------------------

final_segments_files = sorted(FINAL_RELABEL_DIR.glob("*_final_segments.csv"))
final_merged_files = sorted(FINAL_RELABEL_DIR.glob("*_final_merged.csv"))
changed_segments_files = sorted(FINAL_RELABEL_DIR.glob("*_changed_segments.csv"))

# Excluir consolidados globales
final_segments_files = [
    p for p in final_segments_files
    if not p.name.startswith("all_")
]

final_merged_files = [
    p for p in final_merged_files
    if not p.name.startswith("all_")
]

changed_segments_files = [
    p for p in changed_segments_files
    if not p.name.startswith("all_")
]

print("Archivos final_segments encontrados:", len(final_segments_files))
print("Archivos final_merged encontrados:", len(final_merged_files))
print("Archivos changed_segments encontrados:", len(changed_segments_files))

if len(final_segments_files) == 0:
    raise FileNotFoundError(
        "Todavía no hay archivos *_final_segments.csv individuales en final_relabel/."
    )

# ------------------------------------------------------------
# 2. Resumen general del relabeling por audio
# ------------------------------------------------------------

summary_rows = []

for final_path in final_segments_files:
    audio_base = final_path.name.replace("_final_segments.csv", "")
    
    # Seguridad adicional
    if audio_base == "all" or audio_base.startswith("all_"):
        continue
    
    try:
        df_audio = pd.read_csv(final_path)
    except Exception as e:
        print("No se pudo leer:", final_path.name, "|", e)
        continue
    
    n_segments = len(df_audio)
    
    if n_segments == 0:
        continue
    
    if "was_reclassified" in df_audio.columns:
        n_relabelled = int(df_audio["was_reclassified"].fillna(False).astype(bool).sum())
    elif {"speaker_original", "speaker_final"}.issubset(df_audio.columns):
        n_relabelled = int((df_audio["speaker_original"] != df_audio["speaker_final"]).sum())
    else:
        n_relabelled = np.nan
    
    relabel_ratio = n_relabelled / n_segments if n_segments > 0 else np.nan
    
    mean_margin = (
        df_audio["distance_margin"].mean()
        if "distance_margin" in df_audio.columns else np.nan
    )
    
    median_margin = (
        df_audio["distance_margin"].median()
        if "distance_margin" in df_audio.columns else np.nan
    )
    
    max_margin = (
        df_audio["distance_margin"].max()
        if "distance_margin" in df_audio.columns else np.nan
    )
    
    summary_rows.append({
        "audio_base": audio_base,
        "audio_file": audio_base + ".wav",
        "n_segments": n_segments,
        "n_relabelled": n_relabelled,
        "relabel_ratio": relabel_ratio,
        "mean_distance_margin": mean_margin,
        "median_distance_margin": median_margin,
        "max_distance_margin": max_margin,
    })

df_relabeling_summary_by_audio = pd.DataFrame(summary_rows)

if df_relabeling_summary_by_audio.empty:
    raise ValueError("No se pudo construir resumen de relabeling.")

total_audios = df_relabeling_summary_by_audio["audio_base"].nunique()
total_segments = int(df_relabeling_summary_by_audio["n_segments"].sum())
total_relabelled = int(df_relabeling_summary_by_audio["n_relabelled"].sum())
global_relabel_ratio = total_relabelled / total_segments if total_segments > 0 else np.nan

audios_with_relabeling = int((df_relabeling_summary_by_audio["n_relabelled"] > 0).sum())
audios_without_relabeling = total_audios - audios_with_relabeling

print("\n==============================")
print("RESUMEN GENERAL DEL RELABELING")
print("==============================")
print("Audios analizados:", total_audios)
print("Segmentos finales analizados:", total_segments)
print("Segmentos reetiquetados:", total_relabelled)
print("Porcentaje global reetiquetado:", round(global_relabel_ratio * 100, 2), "%")
print("Audios con al menos un segmento reetiquetado:", audios_with_relabeling)
print("Audios sin segmentos reetiquetados:", audios_without_relabeling)

# Guardar resumen
RELABELING_SUMMARY_BY_AUDIO_CSV = FINAL_RELABEL_DIR / "relabeling_summary_by_audio.csv"
df_relabeling_summary_by_audio.to_csv(RELABELING_SUMMARY_BY_AUDIO_CSV, index=False)

print("\nResumen por audio guardado en:")
print(RELABELING_SUMMARY_BY_AUDIO_CSV)

display(
    df_relabeling_summary_by_audio
    .sort_values("n_relabelled", ascending=False)
    .head(15)
)

# ------------------------------------------------------------
# 3. Escoger automáticamente un audio real con relabeling
# ------------------------------------------------------------

df_candidates = (
    df_relabeling_summary_by_audio
    .query("n_relabelled > 0")
    .sort_values(["n_relabelled", "relabel_ratio"], ascending=False)
    .reset_index(drop=True)
)

if df_candidates.empty:
    raise ValueError(
        "No hay audios con segmentos reetiquetados entre los archivos disponibles."
    )

# Verificar que existan los archivos necesarios para build_validation_table
def validation_files_exist(audio_base):
    required_paths = [
        OUTPUT_DIR / f"{audio_base}_raw.csv",
        OUTPUT_DIR / f"{audio_base}.csv",
        OUTPUT_DIR / f"{audio_base}_anchors.csv",
        FINAL_RELABEL_DIR / f"{audio_base}_final_merged.csv",
    ]
    return all(p.exists() for p in required_paths)

df_candidates["files_exist"] = df_candidates["audio_base"].apply(validation_files_exist)
df_candidates = df_candidates[df_candidates["files_exist"]].copy().reset_index(drop=True)

if df_candidates.empty:
    raise ValueError(
        "Hay audios con relabeling, pero ninguno tiene todos los archivos necesarios para construir la tabla maestra."
    )

# IMPORTANTE: usar audio_base, no audio_file
audio_to_validate = df_candidates.loc[0, "audio_base"]

print("\n==============================")
print("AUDIO SELECCIONADO CON RELABELING")
print("==============================")
print("Audio:", audio_to_validate)
print("Segmentos reetiquetados:", int(df_candidates.loc[0, "n_relabelled"]))
print("Ratio reetiquetado:", round(df_candidates.loc[0, "relabel_ratio"] * 100, 2), "%")

# ------------------------------------------------------------
# 4. Construir tabla maestra del audio seleccionado
# ------------------------------------------------------------

df_validation = build_validation_table(audio_to_validate)

cols_to_show = [
    "segment_id_raw",
    "start_raw",
    "end_raw",
    "interval_raw",
    "duration_raw",
    "speaker_raw",
    "speaker_original",
    "speaker_final",
    "was_reclassified",
    "distance_margin",
    "is_anchor",
    "anchor_rank",
    "overlap_ratio",
    "rms_dbfs",
    "valid_export",
    "merge_start",
    "merge_end",
    "merge_speaker_final",
]

cols_to_show = [col for col in cols_to_show if col in df_validation.columns]

print("\nTabla de validación construida correctamente.")
print("Filas:", len(df_validation))
print("Columnas:", len(df_validation.columns))

# Mostrar primero los segmentos que sí cambiaron
if "was_reclassified" in df_validation.columns:
    df_changed_view = df_validation[
        df_validation["was_reclassified"].fillna(False).astype(bool)
    ].copy()
elif {"speaker_original", "speaker_final"}.issubset(df_validation.columns):
    df_changed_view = df_validation[
        df_validation["speaker_original"] != df_validation["speaker_final"]
    ].copy()
else:
    df_changed_view = pd.DataFrame()

print("\nSegmentos reetiquetados en este audio:", len(df_changed_view))

if len(df_changed_view) > 0:
    display(df_changed_view[cols_to_show].head(30))
else:
    display(df_validation[cols_to_show].head(50))

Archivos final_segments encontrados: 1181
Archivos final_merged encontrados: 1181
Archivos changed_segments encontrados: 1181

==============================
RESUMEN GENERAL DEL RELABELING
==============================
Audios analizados: 1181
Segmentos finales analizados: 43493
Segmentos reetiquetados: 3700
Porcentaje global reetiquetado: 8.51 %
Audios con al menos un segmento reetiquetado: 933
Audios sin segmentos reetiquetados: 248

Resumen por audio guardado en:
/home/jupyter/TFM_ProcesadoDeAudios/data/diarization_outputs/final_relabel/relabeling_summary_by_audio.csv

,audio_base,audio_file,n_segments,n_relabelled,relabel_ratio,mean_distance_margin,median_distance_margin,max_distance_margin
742,raw_bajas_9156993504100006851_clean,raw_bajas_9156993504100006851_clean.wav,72,29,0.402778,0.101392,0.107203,0.229827
712,raw_bajas_9156942885910006851_clean,raw_bajas_9156942885910006851_clean.wav,43,21,0.488372,0.198602,0.179826,0.453174
595,raw_bajas_9156702040930006851_clean,raw_bajas_9156702040930006851_clean.wav,48,20,0.416667,0.306338,0.307691,0.517978
189,raw_9156845884280006851_clean,raw_9156845884280006851_clean.wav,46,19,0.413043,0.126758,0.104258,0.329930
24,raw_9154394927400006851_clean,raw_9154394927400006851_clean.wav,72,19,0.263889,0.099602,0.091815,0.234024
210,raw_bajas_9156002528450026851_clean,raw_bajas_9156002528450026851_clean.wav,67,18,0.268657,0.263237,0.249661,0.655054
309,raw_bajas_9156258566490016851_clean,raw_bajas_9156258566490016851_clean.wav,43,18,0.418605,0.076707,0.069167,0.207096
1027,raw_bajas_9157339371880006851_clean,raw_bajas_9157339371880006851_clean.wav,33,17,0.515152,0.099664,0.101173,0.189625
621,raw_bajas_9156762393720006851_clean,raw_bajas_9156762393720006851_clean.wav,67,17,0.253731,0.264040,0.278654,0.537877
375,raw_bajas_9156362641780006851_clean,raw_bajas_9156362641780006851_clean.wav,45,16,0.355556,0.115722,0.097559,0.332058
1069,raw_bajas_9157349989010006851_clean,raw_bajas_9157349989010006851_clean.wav,41,16,0.390244,0.072056,0.048436,0.271835
1014,raw_bajas_9157331666390016851_clean,raw_bajas_9157331666390016851_clean.wav,32,16,0.500000,0.164113,0.144214,0.385716
562,raw_bajas_9156641765810006851_clean,raw_bajas_9156641765810006851_clean.wav,31,15,0.483871,0.233417,0.229801,0.555660
370,raw_bajas_9156337639580026851_clean,raw_bajas_9156337639580026851_clean.wav,39,15,0.384615,0.245739,0.259453,0.449514
164,raw_9156467556910006851_clean,raw_9156467556910006851_clean.wav,48,15,0.312500,0.260349,0.251696,0.511628

==============================
AUDIO SELECCIONADO CON RELABELING
==============================
Audio: raw_bajas_9156993504100006851_clean
Segmentos reetiquetados: 29
Ratio reetiquetado: 40.28 %

Tabla de validación construida correctamente.
Filas: 168
Columnas: 34

Segmentos reetiquetados en este audio: 29

/var/tmp/ipykernel_72187/999496423.py:108: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["is_valid_segment"] = df["is_valid_segment"].fillna(False)
/var/tmp/ipykernel_72187/999496423.py:123: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["is_anchor"] = df["is_anchor"].fillna(False)
/var/tmp/ipykernel_72187/999496423.py:145: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["is_in_changed_sheet"] = df["is_in_changed_sheet"].fillna(False)

,segment_id_raw,start_raw,end_raw,duration_raw,speaker_raw,speaker_original,speaker_final,was_reclassified,distance_margin,is_anchor,anchor_rank,merge_start,merge_end,merge_speaker_final
1,2,1.549719,2.275344,0.725625,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.070518,False,NaN,1.549719,2.275344,SPEAKER_01
12,13,11.033469,11.978469,0.945000,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.057591,False,NaN,11.033469,15.184719,SPEAKER_01
14,15,12.029094,12.974094,0.945000,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.148887,False,NaN,11.033469,15.184719,SPEAKER_01
16,17,13.024719,13.969719,0.945000,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.087801,False,NaN,11.033469,15.184719,SPEAKER_01
18,19,14.037219,15.184719,1.147500,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.080748,False,NaN,11.033469,15.184719,SPEAKER_01
26,27,30.034719,31.300344,1.265625,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.071245,False,NaN,23.470344,31.300344,SPEAKER_01
27,28,31.958469,33.004719,1.046250,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.047153,False,NaN,31.958469,33.004719,SPEAKER_01
29,30,35.789094,37.611594,1.822500,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.105993,False,NaN,33.662844,37.611594,SPEAKER_01
43,44,52.697844,55.380969,2.683125,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.045576,False,NaN,52.697844,58.806594,SPEAKER_01
64,65,88.675344,89.400969,0.725625,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.114599,False,NaN,80.862219,89.400969,SPEAKER_01
68,69,91.037844,91.847844,0.810000,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.059591,False,NaN,91.037844,91.847844,SPEAKER_01
80,81,93.029094,93.974094,0.945000,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.130446,False,NaN,93.029094,95.037219,SPEAKER_01
82,83,94.024719,95.037219,1.012500,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.114897,False,NaN,93.029094,95.037219,SPEAKER_01
92,93,101.635344,102.664719,1.029375,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.032255,False,NaN,96.420969,102.664719,SPEAKER_01
93,94,103.356594,105.567219,2.210625,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.036093,False,NaN,103.356594,109.178469,SPEAKER_01
98,99,114.578469,115.489719,0.911250,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.113167,False,NaN,111.085344,119.252844,SPEAKER_01
102,103,115.928469,117.059094,1.130625,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.032357,False,NaN,111.085344,119.252844,SPEAKER_01
106,107,120.029094,121.851594,1.822500,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.031099,False,NaN,120.029094,126.795969,SPEAKER_01
110,111,128.635344,129.479094,0.843750,SPEAKER_01,SPEAKER_01,SPEAKER_00,True,0.058742,False,NaN,128.635344,129.479094,SPEAKER_00
111,112,130.154094,131.774094,1.620000,SPEAKER_01,SPEAKER_01,SPEAKER_00,True,0.041998,False,NaN,130.154094,131.774094,SPEAKER_00
114,115,139.789719,140.549094,0.759375,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.044241,False,NaN,139.789719,140.549094,SPEAKER_01
119,120,146.235969,147.501594,1.265625,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.039310,False,NaN,146.235969,150.404094,SPEAKER_01
121,122,151.180344,152.935344,1.755000,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.066688,False,NaN,151.180344,152.935344,SPEAKER_01
130,131,176.965344,178.551594,1.586250,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.055068,False,NaN,175.530969,184.137219,SPEAKER_01
136,137,190.515969,192.051594,1.535625,SPEAKER_01,SPEAKER_01,SPEAKER_00,True,0.136350,False,NaN,190.515969,192.051594,SPEAKER_00
142,143,199.864719,201.737844,1.873125,SPEAKER_01,SPEAKER_01,SPEAKER_00,True,0.103938,False,NaN,199.864719,201.737844,SPEAKER_00
157,158,207.542844,208.589094,1.046250,SPEAKER_01,SPEAKER_01,SPEAKER_00,True,0.155499,False,NaN,207.542844,208.589094,SPEAKER_00
163,164,215.828469,216.790344,0.961875,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.117618,False,NaN,215.828469,216.790344,SPEAKER_01
165,166,221.025969,221.802219,0.776250,SPEAKER_00,SPEAKER_00,SPEAKER_01,True,0.073987,False,NaN,217.313469,221.802219,SPEAKER_01

## Estructura final esperada

- `outputs/<nombre_audio>_raw.csv` → segmentos usados para puntuar/limpiar
- `outputs/<nombre_audio>.csv` → segmentos válidos para exportar y escuchar
- `outputs/<nombre_audio>_anchors.csv` → anchors de alta confianza por speaker
- `outputs/<nombre_audio>.rttm`
- `outputs/diarization_summary.csv`
- `outputs/diarization_all_regular_segments.csv`
- `outputs/diarization_all_scored_segments.csv`
- `outputs/diarization_all_valid_segments.csv`
- `outputs/diarization_all_anchor_segments.csv`
- `outputs/segments/<nombre_audio>/...wav`
- `outputs/anchor_segments/<nombre_audio>/...wav`

### Idea de uso
- Los **segmentos válidos** sirven para auditoría general.
- Los **anchors** sirven para la siguiente fase de identificación de speaker/rol.
- El **inicio superpuesto** no se elimina del audio, pero sí se puede excluir del proceso de seleccionar anchors.